import type {
  StorySentence, StoryKeyword, StoryQuizQuestion, StoryGrammarNote,
  StoryDifficulty, StoryCategory,
} from '@lingua-card/shared/domain';

export interface PlatformStorySeedItem {
  id: string;
  title: string;
  titleTranslation: string;
  bodyDe: string;
  bodyNative: string;
  sentences: StorySentence[];
  keywords: StoryKeyword[];
  quizQuestions: StoryQuizQuestion[];
  grammarNotes: StoryGrammarNote[];
  level: StoryDifficulty;
  category: StoryCategory;
  topics: string[];
  isFiction: boolean;
  isPremium: boolean;
  wordCount: number;
  estimatedReadMinutes: number;
  coverGradient: string;
}

// ─── HELPER ───────────────────────────────────────────────────────────────────

function s(index: number, german: string, native: string): StorySentence {
  return { index, german, native, vocabWordIds: [] };
}

function kw(
  german: string, germanBase: string, translation: string,
  article: 'der' | 'die' | 'das' | null,
  wordType: StoryKeyword['wordType'],
  level: StoryKeyword['level'],
): StoryKeyword {
  return { cardId: null, german, germanBase, translation, article, wordType, level };
}

function qq(
  id: string, sentenceTemplate: string, correctAnswer: string,
  distractors: string[], hint?: string,
): StoryQuizQuestion {
  return { id, sentenceTemplate, correctAnswer, distractors, hint };
}

function gn(
  id: string, title: string, exampleDe: string, exampleNative: string,
  description: string, additionalExamples: Array<{ de: string; native: string }> = [],
): StoryGrammarNote {
  return { id, title, exampleDe, exampleNative, description, additionalExamples };
}

// ─── SEED DATA (20 STORIES) ───────────────────────────────────────────────────

export const PLATFORM_STORIES_SEED: PlatformStorySeedItem[] = [

  // ── A1 · Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'ps-a1-daily-001',
    title: 'Ein Tag in Berlin',
    titleTranslation: 'A Day in Berlin',
    level: 'A1', category: 'daily-life', isFiction: false, isPremium: false,
    wordCount: 68, estimatedReadMinutes: 2,
    topics: ['city', 'routine', 'sightseeing'],
    coverGradient: 'linear-gradient(135deg,#3B6F60,#8CB5A4)',
    bodyDe: 'Ich wohne in Berlin. Jeden Morgen stehe ich um sieben Uhr auf. Ich trinke Kaffee und esse Brot mit Butter. Dann fahre ich mit der U-Bahn zur Arbeit. Berlin ist eine große Stadt. Es gibt viele Parks und Museen. Am Nachmittag gehe ich oft im Tiergarten spazieren. Abends koche ich zu Hause. Ich mag Berlin sehr.',
    bodyNative: 'I live in Berlin. Every morning I get up at seven. I drink coffee and eat bread with butter. Then I take the subway to work. Berlin is a big city. There are many parks and museums. In the afternoon I often go for a walk in the Tiergarten. In the evening I cook at home. I like Berlin very much.',
    sentences: [
      s(0,'Ich wohne in Berlin.','I live in Berlin.'),
      s(1,'Jeden Morgen stehe ich um sieben Uhr auf.','Every morning I get up at seven.'),
      s(2,'Ich trinke Kaffee und esse Brot mit Butter.','I drink coffee and eat bread with butter.'),
      s(3,'Dann fahre ich mit der U-Bahn zur Arbeit.','Then I take the subway to work.'),
      s(4,'Berlin ist eine große Stadt.','Berlin is a big city.'),
      s(5,'Es gibt viele Parks und Museen.','There are many parks and museums.'),
      s(6,'Am Nachmittag gehe ich oft im Tiergarten spazieren.','In the afternoon I often go for a walk in the Tiergarten.'),
      s(7,'Abends koche ich zu Hause.','In the evening I cook at home.'),
      s(8,'Ich mag Berlin sehr.','I like Berlin very much.'),
    ],
    keywords: [
      kw('die U-Bahn','U-Bahn','subway / metro','die','noun','A1'),
      kw('die Arbeit','Arbeit','work / job','die','noun','A1'),
      kw('der Park','Park','park','der','noun','A1'),
      kw('das Museum','Museum','museum','das','noun','A1'),
      kw('spazieren gehen','spazieren gehen','to go for a walk',null,'verb','A1'),
      kw('aufstehen','aufstehen','to get up',null,'verb','A1'),
      kw('kochen','kochen','to cook',null,'verb','A1'),
    ],
    quizQuestions: [
      qq('ps-a1-d1-q1','Ich wohne ___ Berlin.','in',['an','bei'],'Locations use "in" for cities.'),
      qq('ps-a1-d1-q2','Ich trinke ___ und esse Brot.','Kaffee',['Wasser','Tee'],'The narrator drinks coffee in the morning.'),
      qq('ps-a1-d1-q3','Dann fahre ich mit der ___ zur Arbeit.','U-Bahn',['Straßenbahn','S-Bahn'],'The narrator takes the subway.'),
      qq('ps-a1-d1-q4','Es gibt viele Parks und ___.','Museen',['Schulen','Kinos'],'Berlin has many parks and museums.'),
      qq('ps-a1-d1-q5','Am ___ gehe ich oft spazieren.','Nachmittag',['Morgen','Abend'],'The walk is in the afternoon.'),
    ],
    grammarNotes: [
      gn('ps-a1-d1-g1','Verb "aufstehen" (separable verb)',
        'Jeden Morgen stehe ich um sieben Uhr auf.',
        'Every morning I get up at seven.',
        'Separable verbs split in the present tense: the prefix goes to the end of the clause. "aufstehen" → "ich stehe … auf".',
        [{ de: 'Er steht spät auf.', native: 'He gets up late.' }]),
      gn('ps-a1-d1-g2','Dative with "mit"',
        'Ich fahre mit der U-Bahn.',
        'I travel by subway.',
        '"mit" (with / by means of) always takes the dative case. "die U-Bahn" becomes "der U-Bahn" in dative.',
        [{ de: 'Sie fährt mit dem Bus.', native: 'She travels by bus.' }]),
    ],
  },

  // ── A1 · Food & Culture ──────────────────────────────────────────────────────
  {
    id: 'ps-a1-food-001',
    title: 'Im Café bestellen',
    titleTranslation: 'Ordering at the Café',
    level: 'A1', category: 'food-culture', isFiction: false, isPremium: false,
    wordCount: 60, estimatedReadMinutes: 2,
    topics: ['café', 'ordering', 'food'],
    coverGradient: 'linear-gradient(135deg,#8B4513,#D4A96A)',
    bodyDe: 'Lena geht ins Café. Sie setzt sich an einen Tisch. Der Kellner kommt. "Was möchten Sie?" fragt er. "Einen Kaffee und ein Stück Kuchen, bitte," sagt Lena. "Welchen Kuchen möchten Sie? Wir haben Apfelkuchen und Schokoladenkuchen." "Apfelkuchen, bitte," antwortet Lena. Der Kellner bringt den Kaffee und den Kuchen. Lena trinkt den Kaffee und isst den Kuchen. Er schmeckt sehr gut. Sie bezahlt und geht.',
    bodyNative: 'Lena goes to the café. She sits down at a table. The waiter comes. "What would you like?" he asks. "A coffee and a piece of cake, please," says Lena. "Which cake would you like? We have apple cake and chocolate cake." "Apple cake, please," Lena replies. The waiter brings the coffee and the cake. Lena drinks the coffee and eats the cake. It tastes very good. She pays and leaves.',
    sentences: [
      s(0,'Lena geht ins Café.','Lena goes to the café.'),
      s(1,'Sie setzt sich an einen Tisch.','She sits down at a table.'),
      s(2,'Der Kellner kommt.','The waiter comes.'),
      s(3,'"Was möchten Sie?" fragt er.','"What would you like?" he asks.'),
      s(4,'"Einen Kaffee und ein Stück Kuchen, bitte," sagt Lena.','"A coffee and a piece of cake, please," says Lena.'),
      s(5,'"Welchen Kuchen möchten Sie? Wir haben Apfelkuchen und Schokoladenkuchen."','"Which cake would you like? We have apple cake and chocolate cake."'),
      s(6,'"Apfelkuchen, bitte," antwortet Lena.','"Apple cake, please," Lena replies.'),
      s(7,'Der Kellner bringt den Kaffee und den Kuchen.','The waiter brings the coffee and the cake.'),
      s(8,'Lena trinkt den Kaffee und isst den Kuchen.','Lena drinks the coffee and eats the cake.'),
      s(9,'Er schmeckt sehr gut.','It tastes very good.'),
      s(10,'Sie bezahlt und geht.','She pays and leaves.'),
    ],
    keywords: [
      kw('der Kellner','Kellner','waiter','der','noun','A1'),
      kw('das Stück','Stück','piece','das','noun','A1'),
      kw('der Kuchen','Kuchen','cake','der','noun','A1'),
      kw('der Apfelkuchen','Apfelkuchen','apple cake','der','noun','A1'),
      kw('schmecken','schmecken','to taste',null,'verb','A1'),
      kw('bezahlen','bezahlen','to pay',null,'verb','A1'),
      kw('bestellen','bestellen','to order',null,'verb','A1'),
      kw('möchten','möchten','would like',null,'verb','A1'),
    ],
    quizQuestions: [
      qq('ps-a1-f1-q1','Lena setzt sich ___ einen Tisch.','an',['auf','in'],'She sits down at a table — "an" + accusative.'),
      qq('ps-a1-f1-q2','Sie möchte einen Kaffee und ein Stück ___.','Kuchen',['Brot','Eis'],'Lena orders a piece of cake.'),
      qq('ps-a1-f1-q3','Der Kellner ___ den Kaffee und den Kuchen.','bringt',['kauft','macht'],'The waiter brings the order.'),
      qq('ps-a1-f1-q4','Der Kuchen ___ sehr gut.','schmeckt',['kostet','riecht'],'It tastes very good.'),
      qq('ps-a1-f1-q5','Am Ende ___ Lena und geht.','bezahlt',['wartet','sitzt'],'She pays and leaves.'),
    ],
    grammarNotes: [
      gn('ps-a1-f1-g1','Accusative after "möchten"',
        'Einen Kaffee und ein Stück Kuchen, bitte.',
        'A coffee and a piece of cake, please.',
        'After modal verbs like "möchten", the direct object takes the accusative case. Masculine "der Kaffee" → "einen Kaffee".',
        [{ de: 'Ich möchte einen Tee.', native: 'I would like a tea.' }]),
    ],
  },

  // ── A1 · Fiction ─────────────────────────────────────────────────────────────
  {
    id: 'ps-a1-fiction-001',
    title: 'Der kleine Hund Max',
    titleTranslation: 'The Little Dog Max',
    level: 'A1', category: 'fiction', isFiction: true, isPremium: false,
    wordCount: 65, estimatedReadMinutes: 2,
    topics: ['animals', 'children', 'friendship'],
    coverGradient: 'linear-gradient(135deg,#5B7FA6,#A8C8E8)',
    bodyDe: 'Max ist ein kleiner Hund. Er ist weiß und braun. Max wohnt bei der Familie Müller. Er hat eine rote Leine. Jeden Tag geht Max mit Anna in den Park. Anna wirft einen Ball. Max läuft und holt den Ball. "Guter Hund!", sagt Anna. Max wedelt mit dem Schwanz. Er ist sehr glücklich.',
    bodyNative: 'Max is a little dog. He is white and brown. Max lives with the Müller family. He has a red leash. Every day Max goes to the park with Anna. Anna throws a ball. Max runs and fetches the ball. "Good dog!" says Anna. Max wags his tail. He is very happy.',
    sentences: [
      s(0,'Max ist ein kleiner Hund.','Max is a little dog.'),
      s(1,'Er ist weiß und braun.','He is white and brown.'),
      s(2,'Max wohnt bei der Familie Müller.','Max lives with the Müller family.'),
      s(3,'Er hat eine rote Leine.','He has a red leash.'),
      s(4,'Jeden Tag geht Max mit Anna in den Park.','Every day Max goes to the park with Anna.'),
      s(5,'Anna wirft einen Ball.','Anna throws a ball.'),
      s(6,'Max läuft und holt den Ball.','Max runs and fetches the ball.'),
      s(7,'"Guter Hund!", sagt Anna.','"Good dog!" says Anna.'),
      s(8,'Max wedelt mit dem Schwanz.','Max wags his tail.'),
      s(9,'Er ist sehr glücklich.','He is very happy.'),
    ],
    keywords: [
      kw('die Leine','Leine','leash','die','noun','A1'),
      kw('der Ball','Ball','ball','der','noun','A1'),
      kw('der Schwanz','Schwanz','tail','der','noun','A1'),
      kw('werfen','werfen','to throw',null,'verb','A1'),
      kw('holen','holen','to fetch / get',null,'verb','A1'),
      kw('wedeln','wedeln','to wag',null,'verb','A1'),
      kw('glücklich','glücklich','happy',null,'adjective','A1'),
    ],
    quizQuestions: [
      qq('ps-a1-fi1-q1','Max ist ein kleiner ___.','Hund',['Katz','Vogel'],'Max is a dog.'),
      qq('ps-a1-fi1-q2','Er hat eine rote ___.','Leine',['Jacke','Tasche'],'Max has a red leash.'),
      qq('ps-a1-fi1-q3','Anna ___ einen Ball.','wirft',['kauft','findet'],'Anna throws the ball.'),
      qq('ps-a1-fi1-q4','Max ___ mit dem Schwanz.','wedelt',['läuft','schläft'],'Max wags his tail.'),
      qq('ps-a1-fi1-q5','Er ist sehr ___.','glücklich',['traurig','müde'],'He is very happy.'),
    ],
    grammarNotes: [
      gn('ps-a1-fi1-g1','Adjective endings (attributive)',
        'Max ist ein kleiner Hund.',
        'Max is a little dog.',
        'Adjectives before nouns need an ending. After "ein" (indefinite article), masculine nominative takes "-er": "ein kleiner Hund".',
        [{ de: 'Das ist ein großes Haus.', native: 'That is a big house.' }]),
    ],
  },

  // ── A1 · Travel ──────────────────────────────────────────────────────────────
  {
    id: 'ps-a1-travel-001',
    title: 'Am Bahnhof',
    titleTranslation: 'At the Train Station',
    level: 'A1', category: 'travel', isFiction: false, isPremium: false,
    wordCount: 62, estimatedReadMinutes: 2,
    topics: ['train', 'station', 'tickets'],
    coverGradient: 'linear-gradient(135deg,#3B6F60,#8CB5A4)',
    bodyDe: 'Tom ist am Bahnhof. Er möchte nach München fahren. Er geht zum Schalter. "Einmal nach München, bitte," sagt er. "Einfach oder hin und zurück?" fragt die Frau. "Hin und zurück, bitte." Die Fahrkarte kostet zwanzig Euro. Tom bezahlt und nimmt die Fahrkarte. Sein Zug fährt in zehn Minuten ab. Er geht zu Gleis vier.',
    bodyNative: 'Tom is at the train station. He wants to travel to Munich. He goes to the counter. "One ticket to Munich, please," he says. "Single or return?" asks the woman. "Return, please." The ticket costs twenty euros. Tom pays and takes the ticket. His train departs in ten minutes. He goes to platform four.',
    sentences: [
      s(0,'Tom ist am Bahnhof.','Tom is at the train station.'),
      s(1,'Er möchte nach München fahren.','He wants to travel to Munich.'),
      s(2,'Er geht zum Schalter.','He goes to the counter.'),
      s(3,'"Einmal nach München, bitte," sagt er.','"One ticket to Munich, please," he says.'),
      s(4,'"Einfach oder hin und zurück?" fragt die Frau.','"Single or return?" asks the woman.'),
      s(5,'"Hin und zurück, bitte."','"Return, please."'),
      s(6,'Die Fahrkarte kostet zwanzig Euro.','The ticket costs twenty euros.'),
      s(7,'Tom bezahlt und nimmt die Fahrkarte.','Tom pays and takes the ticket.'),
      s(8,'Sein Zug fährt in zehn Minuten ab.','His train departs in ten minutes.'),
      s(9,'Er geht zu Gleis vier.','He goes to platform four.'),
    ],
    keywords: [
      kw('der Bahnhof','Bahnhof','train station','der','noun','A1'),
      kw('die Fahrkarte','Fahrkarte','ticket','die','noun','A1'),
      kw('der Schalter','Schalter','counter / ticket window','der','noun','A1'),
      kw('das Gleis','Gleis','platform / track','das','noun','A1'),
      kw('abfahren','abfahren','to depart',null,'verb','A1'),
      kw('kosten','kosten','to cost',null,'verb','A1'),
      kw('hin und zurück','hin und zurück','return (round trip)',null,'other','A1'),
    ],
    quizQuestions: [
      qq('ps-a1-t1-q1','Tom ist am ___.','Bahnhof',['Flughafen','Hafen'],'He is at the train station.'),
      qq('ps-a1-t1-q2','Er geht zum ___.','Schalter',['Gleis','Ausgang'],'He goes to the ticket counter.'),
      qq('ps-a1-t1-q3','Die Fahrkarte ___ zwanzig Euro.','kostet',['hat','macht'],'The ticket costs twenty euros.'),
      qq('ps-a1-t1-q4','Sein Zug fährt in zehn Minuten ___.','ab',['an','ein'],'Separable verb "abfahren" — "ab" goes to end.'),
      qq('ps-a1-t1-q5','Er geht zu ___ vier.','Gleis',['Bahn','Zug'],'He goes to platform four.'),
    ],
    grammarNotes: [
      gn('ps-a1-t1-g1','Modal verb "möchten" + infinitive',
        'Er möchte nach München fahren.',
        'He wants to travel to Munich.',
        '"möchten" is a modal verb meaning "would like to". The second verb (the action) is an infinitive at the end of the sentence.',
        [{ de: 'Ich möchte Deutsch lernen.', native: 'I would like to learn German.' }]),
    ],
  },

  // ── A2 · Work & Career ───────────────────────────────────────────────────────
  {
    id: 'ps-a2-work-001',
    title: 'Mein erster Arbeitstag',
    titleTranslation: 'My First Day at Work',
    level: 'A2', category: 'work-career', isFiction: false, isPremium: false,
    wordCount: 78, estimatedReadMinutes: 2,
    topics: ['office', 'first day', 'colleagues'],
    coverGradient: 'linear-gradient(135deg,#4A3728,#8B6D5A)',
    bodyDe: 'Heute ist mein erster Arbeitstag. Ich bin sehr aufgeregt. Das Büro ist modern und hell. Meine Kollegin Sandra zeigt mir alles. "Das ist die Küche. Dort kannst du Kaffee machen," sagt sie. Ich lerne viele neue Kollegen kennen. Wir haben eine kurze Besprechung um zehn Uhr. Der Chef heißt Herr Weber und ist sehr freundlich. Nach der Arbeit bin ich müde, aber glücklich.',
    bodyNative: 'Today is my first day at work. I am very excited. The office is modern and bright. My colleague Sandra shows me everything. "That is the kitchen. You can make coffee there," she says. I meet many new colleagues. We have a short meeting at ten. The boss is called Mr Weber and is very friendly. After work I am tired but happy.',
    sentences: [
      s(0,'Heute ist mein erster Arbeitstag.','Today is my first day at work.'),
      s(1,'Ich bin sehr aufgeregt.','I am very excited.'),
      s(2,'Das Büro ist modern und hell.','The office is modern and bright.'),
      s(3,'Meine Kollegin Sandra zeigt mir alles.','My colleague Sandra shows me everything.'),
      s(4,'"Das ist die Küche. Dort kannst du Kaffee machen," sagt sie.','"That is the kitchen. You can make coffee there," she says.'),
      s(5,'Ich lerne viele neue Kollegen kennen.','I meet many new colleagues.'),
      s(6,'Wir haben eine kurze Besprechung um zehn Uhr.','We have a short meeting at ten.'),
      s(7,'Der Chef heißt Herr Weber und ist sehr freundlich.','The boss is called Mr Weber and is very friendly.'),
      s(8,'Nach der Arbeit bin ich müde, aber glücklich.','After work I am tired but happy.'),
    ],
    keywords: [
      kw('die Kollegin','Kollegin','female colleague','die','noun','A2'),
      kw('das Büro','Büro','office','das','noun','A2'),
      kw('die Besprechung','Besprechung','meeting','die','noun','A2'),
      kw('der Chef','Chef','boss','der','noun','A2'),
      kw('aufgeregt','aufgeregt','excited',null,'adjective','A2'),
      kw('kennenlernen','kennenlernen','to get to know / meet',null,'verb','A2'),
      kw('zeigen','zeigen','to show',null,'verb','A2'),
    ],
    quizQuestions: [
      qq('ps-a2-w1-q1','Das ___ ist modern und hell.','Büro',['Haus','Zimmer'],'The office is modern and bright.'),
      qq('ps-a2-w1-q2','Sandra zeigt ___ alles.','mir',['mich','mein'],'Dative pronoun after "zeigen" (to show somebody something).'),
      qq('ps-a2-w1-q3','Ich lerne viele neue Kollegen ___.','kennen',['kennt','kannte'],'Separable verb "kennenlernen" — "kennen" at end.'),
      qq('ps-a2-w1-q4','Wir haben eine kurze ___ um zehn Uhr.','Besprechung',['Pause','Stunde'],'They have a meeting at ten.'),
      qq('ps-a2-w1-q5','Nach ___ Arbeit bin ich müde.','der',['die','den'],'After a preposition requiring dative, "die Arbeit" → "der Arbeit".'),
    ],
    grammarNotes: [
      gn('ps-a2-w1-g1','Modal verb "können" + infinitive',
        'Dort kannst du Kaffee machen.',
        'You can make coffee there.',
        '"können" expresses ability or permission. The infinitive ("machen") goes to the end of the clause.',
        [{ de: 'Er kann gut kochen.', native: 'He can cook well.' }]),
      gn('ps-a2-w1-g2','Dative pronoun "mir"',
        'Meine Kollegin zeigt mir alles.',
        'My colleague shows me everything.',
        '"zeigen" takes two objects: a dative person and an accusative thing. "mir" = "me" in the dative case.',
        [{ de: 'Er gibt mir das Buch.', native: 'He gives me the book.' }]),
    ],
  },

  // ── A2 · Technology ──────────────────────────────────────────────────────────
  {
    id: 'ps-a2-tech-001',
    title: 'Das neue Handy',
    titleTranslation: 'The New Phone',
    level: 'A2', category: 'technology', isFiction: false, isPremium: false,
    wordCount: 72, estimatedReadMinutes: 2,
    topics: ['smartphone', 'shopping', 'apps'],
    coverGradient: 'linear-gradient(135deg,#2C3E50,#4CA1AF)',
    bodyDe: 'Julia hat sich ein neues Handy gekauft. Es ist ein Smartphone mit einem großen Bildschirm. Sie lädt zuerst ihre Lieblings-Apps herunter. Mit der Kamera macht sie tolle Fotos. Sie schreibt Nachrichten an ihre Freunde. "Schick mir doch ein Foto!", schreibt ihr Freund Leon. Julia schickt ihm ein Selfie. Der Akku hält fast zwei Tage. Das neue Handy gefällt ihr sehr.',
    bodyNative: 'Julia has bought herself a new phone. It is a smartphone with a large screen. She first downloads her favourite apps. She takes great photos with the camera. She writes messages to her friends. "Send me a photo!" writes her friend Leon. Julia sends him a selfie. The battery lasts almost two days. She likes the new phone very much.',
    sentences: [
      s(0,'Julia hat sich ein neues Handy gekauft.','Julia has bought herself a new phone.'),
      s(1,'Es ist ein Smartphone mit einem großen Bildschirm.','It is a smartphone with a large screen.'),
      s(2,'Sie lädt zuerst ihre Lieblings-Apps herunter.','She first downloads her favourite apps.'),
      s(3,'Mit der Kamera macht sie tolle Fotos.','She takes great photos with the camera.'),
      s(4,'Sie schreibt Nachrichten an ihre Freunde.','She writes messages to her friends.'),
      s(5,'"Schick mir doch ein Foto!", schreibt ihr Freund Leon.','"Send me a photo!" writes her friend Leon.'),
      s(6,'Julia schickt ihm ein Selfie.','Julia sends him a selfie.'),
      s(7,'Der Akku hält fast zwei Tage.','The battery lasts almost two days.'),
      s(8,'Das neue Handy gefällt ihr sehr.','She likes the new phone very much.'),
    ],
    keywords: [
      kw('das Handy','Handy','mobile phone','das','noun','A2'),
      kw('der Bildschirm','Bildschirm','screen','der','noun','A2'),
      kw('die Kamera','Kamera','camera','die','noun','A2'),
      kw('der Akku','Akku','battery','der','noun','A2'),
      kw('herunterladen','herunterladen','to download',null,'verb','A2'),
      kw('schicken','schicken','to send',null,'verb','A2'),
      kw('gefallen','gefallen','to like (be pleasing to)',null,'verb','A2'),
    ],
    quizQuestions: [
      qq('ps-a2-t1-q1','Es ist ein Smartphone mit einem großen ___.','Bildschirm',['Knopf','Kabel'],'It has a large screen.'),
      qq('ps-a2-t1-q2','Sie lädt ihre Lieblings-Apps ___.','herunter',['hoch','ein'],'Separable verb "herunterladen" — prefix at end.'),
      qq('ps-a2-t1-q3','Julia schickt ___ ein Selfie.','ihm',['ihn','er'],'Dative pronoun for "to him" after "schicken".'),
      qq('ps-a2-t1-q4','Der Akku ___ fast zwei Tage.','hält',['dauert','bleibt'],'The battery lasts two days — "halten" is used here.'),
      qq('ps-a2-t1-q5','Das neue Handy ___ ihr sehr.','gefällt',['mögt','liebt'],'Dative construction: "gefallen" — the phone is pleasing to her.'),
    ],
    grammarNotes: [
      gn('ps-a2-t1-g1','Perfect tense (Perfekt)',
        'Julia hat sich ein neues Handy gekauft.',
        'Julia has bought herself a new phone.',
        'Perfekt = "haben/sein" + past participle. For most verbs use "haben". The participle goes to the end: "ge-" + stem + "-t".',
        [{ de: 'Er hat ein Buch gelesen.', native: 'He has read a book.' }]),
      gn('ps-a2-t1-g2','Dative verb "gefallen"',
        'Das Handy gefällt ihr sehr.',
        'She likes the phone very much.',
        '"gefallen" means "to be pleasing to". The person is in the dative case. Literally: "The phone is pleasing to her."',
        [{ de: 'Gefällt dir die Stadt?', native: 'Do you like the city?' }]),
    ],
  },

  // ── A2 · Health & Fitness ────────────────────────────────────────────────────
  {
    id: 'ps-a2-health-001',
    title: 'Beim Arzt',
    titleTranslation: 'At the Doctor',
    level: 'A2', category: 'health-fitness', isFiction: false, isPremium: false,
    wordCount: 70, estimatedReadMinutes: 2,
    topics: ['doctor', 'illness', 'appointment'],
    coverGradient: 'linear-gradient(135deg,#1A6B4A,#5DB485)',
    bodyDe: 'Klaus fühlt sich nicht gut. Er hat Halsschmerzen und Fieber. Er ruft beim Arzt an und macht einen Termin. Am nächsten Tag geht er in die Praxis. Die Sprechstundenhilfe nimmt seine Krankenkassenkarte. "Wie lange haben Sie schon Schmerzen?", fragt der Arzt. "Seit drei Tagen," antwortet Klaus. Der Arzt untersucht ihn und verschreibt ihm ein Antibiotikum. "Trinken Sie viel Wasser und schlafen Sie viel," sagt er.',
    bodyNative: 'Klaus does not feel well. He has a sore throat and a fever. He calls the doctor and makes an appointment. The next day he goes to the practice. The receptionist takes his health insurance card. "How long have you had the pain?" asks the doctor. "For three days," Klaus replies. The doctor examines him and prescribes an antibiotic. "Drink plenty of water and sleep a lot," he says.',
    sentences: [
      s(0,'Klaus fühlt sich nicht gut.','Klaus does not feel well.'),
      s(1,'Er hat Halsschmerzen und Fieber.','He has a sore throat and a fever.'),
      s(2,'Er ruft beim Arzt an und macht einen Termin.','He calls the doctor and makes an appointment.'),
      s(3,'Am nächsten Tag geht er in die Praxis.','The next day he goes to the practice.'),
      s(4,'Die Sprechstundenhilfe nimmt seine Krankenkassenkarte.','The receptionist takes his health insurance card.'),
      s(5,'"Wie lange haben Sie schon Schmerzen?", fragt der Arzt.','"How long have you had the pain?" asks the doctor.'),
      s(6,'"Seit drei Tagen," antwortet Klaus.','"For three days," Klaus replies.'),
      s(7,'Der Arzt untersucht ihn und verschreibt ihm ein Antibiotikum.','The doctor examines him and prescribes an antibiotic.'),
      s(8,'"Trinken Sie viel Wasser und schlafen Sie viel," sagt er.','"Drink plenty of water and sleep a lot," he says.'),
    ],
    keywords: [
      kw('die Halsschmerzen','Halsschmerzen','sore throat','die','noun','A2'),
      kw('das Fieber','Fieber','fever','das','noun','A2'),
      kw('der Termin','Termin','appointment','der','noun','A2'),
      kw('die Praxis','Praxis','doctor\'s practice','die','noun','A2'),
      kw('das Antibiotikum','Antibiotikum','antibiotic','das','noun','A2'),
      kw('anrufen','anrufen','to call (phone)',null,'verb','A2'),
      kw('verschreiben','verschreiben','to prescribe',null,'verb','A2'),
      kw('untersuchen','untersuchen','to examine',null,'verb','A2'),
    ],
    quizQuestions: [
      qq('ps-a2-h1-q1','Klaus fühlt ___ nicht gut.','sich',['ihm','ihn'],'Reflexive verb "sich fühlen" — reflexive pronoun "sich".'),
      qq('ps-a2-h1-q2','Er macht einen ___.','Termin',['Arzt','Schmerz'],'He makes a doctor\'s appointment.'),
      qq('ps-a2-h1-q3','Seit ___ Tagen hat er Schmerzen.','drei',['zwei','vier'],'He has had pain for three days.'),
      qq('ps-a2-h1-q4','Der Arzt ___ ihm ein Antibiotikum.','verschreibt',['gibt','bringt'],'The doctor prescribes an antibiotic.'),
      qq('ps-a2-h1-q5','Er ruft ___ Arzt an.','beim',['zum','dem'],'Contracted dative: "bei dem Arzt" → "beim Arzt".'),
    ],
    grammarNotes: [
      gn('ps-a2-h1-g1','Reflexive verbs',
        'Klaus fühlt sich nicht gut.',
        'Klaus does not feel well.',
        'Some German verbs require a reflexive pronoun. "sich fühlen" = to feel (oneself). The reflexive pronoun matches the subject.',
        [{ de: 'Ich fühle mich müde.', native: 'I feel tired.' },
         { de: 'Er fühlt sich krank.', native: 'He feels ill.' }]),
      gn('ps-a2-h1-g2','Temporal "seit" + present tense',
        '"Seit drei Tagen," antwortet Klaus.',
        '"For three days," Klaus replies.',
        'German uses "seit" + present tense for ongoing situations (unlike English past tense). "Seit drei Tagen habe ich Schmerzen."',
        [{ de: 'Ich lerne seit einem Jahr Deutsch.', native: 'I have been learning German for a year.' }]),
    ],
  },

  // ── A2 · Fiction ─────────────────────────────────────────────────────────────
  {
    id: 'ps-a2-fiction-001',
    title: 'Die geheimnisvolle Tür',
    titleTranslation: 'The Mysterious Door',
    level: 'A2', category: 'fiction', isFiction: true, isPremium: false,
    wordCount: 80, estimatedReadMinutes: 2,
    topics: ['mystery', 'discovery', 'adventure'],
    coverGradient: 'linear-gradient(135deg,#2D1B69,#6B3FA0)',
    bodyDe: 'Mia findet in ihrem alten Haus eine Tür, die sie noch nie gesehen hat. Die Tür ist aus dunklem Holz und hat ein goldenes Schloss. Sie sucht überall nach dem Schlüssel. Im Keller findet sie eine alte Holzkiste. Darin liegt ein kleiner goldener Schlüssel. Ihr Herz schlägt schneller. Sie geht zurück zur Tür und steckt den Schlüssel ins Schloss. Die Tür öffnet sich langsam. Dahinter liegt ein wunderschöner Garten.',
    bodyNative: 'Mia finds a door in her old house that she has never seen before. The door is made of dark wood and has a golden lock. She searches everywhere for the key. In the cellar she finds an old wooden chest. Inside lies a small golden key. Her heart beats faster. She goes back to the door and puts the key in the lock. The door opens slowly. Behind it lies a beautiful garden.',
    sentences: [
      s(0,'Mia findet in ihrem alten Haus eine Tür, die sie noch nie gesehen hat.','Mia finds a door in her old house that she has never seen before.'),
      s(1,'Die Tür ist aus dunklem Holz und hat ein goldenes Schloss.','The door is made of dark wood and has a golden lock.'),
      s(2,'Sie sucht überall nach dem Schlüssel.','She searches everywhere for the key.'),
      s(3,'Im Keller findet sie eine alte Holzkiste.','In the cellar she finds an old wooden chest.'),
      s(4,'Darin liegt ein kleiner goldener Schlüssel.','Inside lies a small golden key.'),
      s(5,'Ihr Herz schlägt schneller.','Her heart beats faster.'),
      s(6,'Sie geht zurück zur Tür und steckt den Schlüssel ins Schloss.','She goes back to the door and puts the key in the lock.'),
      s(7,'Die Tür öffnet sich langsam.','The door opens slowly.'),
      s(8,'Dahinter liegt ein wunderschöner Garten.','Behind it lies a beautiful garden.'),
    ],
    keywords: [
      kw('die Tür','Tür','door','die','noun','A2'),
      kw('das Schloss','Schloss','lock / castle','das','noun','A2'),
      kw('der Schlüssel','Schlüssel','key','der','noun','A2'),
      kw('der Keller','Keller','cellar','der','noun','A2'),
      kw('die Kiste','Kiste','chest / crate','die','noun','A2'),
      kw('geheimnisvoll','geheimnisvoll','mysterious',null,'adjective','A2'),
      kw('stecken','stecken','to put / insert',null,'verb','A2'),
      kw('öffnen','öffnen','to open',null,'verb','A2'),
    ],
    quizQuestions: [
      qq('ps-a2-fi1-q1','Die Tür ist aus dunklem ___.','Holz',['Stein','Metall'],'The door is made of dark wood.'),
      qq('ps-a2-fi1-q2','Sie sucht überall ___ dem Schlüssel.','nach',['für','von'],'Searching for something: "suchen nach" + dative.'),
      qq('ps-a2-fi1-q3','Im ___ findet sie eine alte Kiste.','Keller',['Garten','Dach'],'She finds the chest in the cellar.'),
      qq('ps-a2-fi1-q4','Ihr Herz ___ schneller.','schlägt',['läuft','dreht'],'Her heart beats faster.'),
      qq('ps-a2-fi1-q5','___ liegt ein wunderschöner Garten.','Dahinter',['Davor','Darin'],'Behind the door lies the garden.'),
    ],
    grammarNotes: [
      gn('ps-a2-fi1-g1','Relative clause with "die"',
        'Eine Tür, die sie noch nie gesehen hat.',
        'A door that she has never seen before.',
        'Relative clauses describe nouns. The relative pronoun matches the gender of the noun: "die Tür" → "die". The verb goes to the end of the relative clause.',
        [{ de: 'Das ist der Mann, der hier wohnt.', native: 'That is the man who lives here.' }]),
    ],
  },

  // ── A2 · Entertainment ───────────────────────────────────────────────────────
  {
    id: 'ps-a2-ent-001',
    title: 'Kinoabend mit Freunden',
    titleTranslation: 'Movie Night with Friends',
    level: 'A2', category: 'entertainment', isFiction: false, isPremium: false,
    wordCount: 74, estimatedReadMinutes: 2,
    topics: ['cinema', 'friends', 'weekend'],
    coverGradient: 'linear-gradient(135deg,#1A1A2E,#E94560)',
    bodyDe: 'Am Freitagabend gehen Tim und seine Freunde ins Kino. Sie wollen einen neuen Actionfilm sehen. Tim kauft die Karten online. Die Karten kosten zwölf Euro pro Person. Im Kino kaufen sie Popcorn und Cola. Der Film beginnt um acht Uhr. Er ist sehr spannend. Am Ende klatschen alle Zuschauer. "Das war der beste Film des Jahres!", sagt Tims Freundin Sara.',
    bodyNative: 'On Friday evening Tim and his friends go to the cinema. They want to see a new action film. Tim buys the tickets online. The tickets cost twelve euros per person. At the cinema they buy popcorn and cola. The film starts at eight. It is very exciting. At the end all the audience applauds. "That was the best film of the year!" says Tim\'s friend Sara.',
    sentences: [
      s(0,'Am Freitagabend gehen Tim und seine Freunde ins Kino.','On Friday evening Tim and his friends go to the cinema.'),
      s(1,'Sie wollen einen neuen Actionfilm sehen.','They want to see a new action film.'),
      s(2,'Tim kauft die Karten online.','Tim buys the tickets online.'),
      s(3,'Die Karten kosten zwölf Euro pro Person.','The tickets cost twelve euros per person.'),
      s(4,'Im Kino kaufen sie Popcorn und Cola.','At the cinema they buy popcorn and cola.'),
      s(5,'Der Film beginnt um acht Uhr.','The film starts at eight.'),
      s(6,'Er ist sehr spannend.','It is very exciting.'),
      s(7,'Am Ende klatschen alle Zuschauer.','At the end all the audience applauds.'),
      s(8,'"Das war der beste Film des Jahres!", sagt Tims Freundin Sara.','"That was the best film of the year!" says Tim\'s friend Sara.'),
    ],
    keywords: [
      kw('das Kino','Kino','cinema','das','noun','A2'),
      kw('die Karte','Karte','ticket','die','noun','A2'),
      kw('spannend','spannend','exciting',null,'adjective','A2'),
      kw('der Zuschauer','Zuschauer','audience member / viewer','der','noun','A2'),
      kw('klatschen','klatschen','to applaud / clap',null,'verb','A2'),
      kw('beginnen','beginnen','to begin / start',null,'verb','A2'),
      kw('der Actionfilm','Actionfilm','action film','der','noun','A2'),
    ],
    quizQuestions: [
      qq('ps-a2-e1-q1','Sie wollen einen neuen Actionfilm ___.','sehen',['gehen','kaufen'],'Modal verb "wollen" + infinitive at end.'),
      qq('ps-a2-e1-q2','Die Karten ___ zwölf Euro pro Person.','kosten',['haben','sind'],'The tickets cost twelve euros.'),
      qq('ps-a2-e1-q3','Der Film ___ um acht Uhr.','beginnt',['endet','startet'],'The film begins at eight.'),
      qq('ps-a2-e1-q4','Am Ende ___ alle Zuschauer.','klatschen',['sehen','stehen'],'The audience applauds at the end.'),
      qq('ps-a2-e1-q5','Das war der ___ Film des Jahres.','beste',['gute','bessere'],'Superlative: best = "beste".'),
    ],
    grammarNotes: [
      gn('ps-a2-e1-g1','Modal verb "wollen" + infinitive',
        'Sie wollen einen neuen Actionfilm sehen.',
        'They want to see a new action film.',
        '"wollen" expresses a strong wish or intention. The infinitive goes to the end. "wollen" conjugates: ich will, du willst, er/sie/es will, wir wollen.',
        [{ de: 'Ich will Deutsch lernen.', native: 'I want to learn German.' }]),
    ],
  },

  // ── A2 · Education ───────────────────────────────────────────────────────────
  {
    id: 'ps-a2-edu-001',
    title: 'Im Deutschkurs',
    titleTranslation: 'In the German Class',
    level: 'A2', category: 'education', isFiction: false, isPremium: false,
    wordCount: 72, estimatedReadMinutes: 2,
    topics: ['language learning', 'classroom', 'students'],
    coverGradient: 'linear-gradient(135deg,#1565C0,#42A5F5)',
    bodyDe: 'María kommt aus Spanien und lernt Deutsch. Sie besucht einen Kurs an der Volkshochschule. Die Lehrerin heißt Frau Braun. Im Kurs sind zwölf Teilnehmer aus verschiedenen Ländern. Heute üben sie Dialog. María spielt eine Szene im Supermarkt. Sie macht ein paar Fehler, aber die Lehrerin hilft ihr. "Dein Deutsch wird immer besser!", sagt Frau Braun. María freut sich sehr.',
    bodyNative: 'María comes from Spain and is learning German. She attends a course at the adult education centre. The teacher is called Ms Braun. In the course there are twelve participants from different countries. Today they practise dialogue. María acts out a scene in the supermarket. She makes a few mistakes but the teacher helps her. "Your German is getting better and better!" says Ms Braun. María is very pleased.',
    sentences: [
      s(0,'María kommt aus Spanien und lernt Deutsch.','María comes from Spain and is learning German.'),
      s(1,'Sie besucht einen Kurs an der Volkshochschule.','She attends a course at the adult education centre.'),
      s(2,'Die Lehrerin heißt Frau Braun.','The teacher is called Ms Braun.'),
      s(3,'Im Kurs sind zwölf Teilnehmer aus verschiedenen Ländern.','In the course there are twelve participants from different countries.'),
      s(4,'Heute üben sie Dialog.','Today they practise dialogue.'),
      s(5,'María spielt eine Szene im Supermarkt.','María acts out a scene in the supermarket.'),
      s(6,'Sie macht ein paar Fehler, aber die Lehrerin hilft ihr.','She makes a few mistakes but the teacher helps her.'),
      s(7,'"Dein Deutsch wird immer besser!", sagt Frau Braun.','"Your German is getting better and better!" says Ms Braun.'),
      s(8,'María freut sich sehr.','María is very pleased.'),
    ],
    keywords: [
      kw('die Volkshochschule','Volkshochschule','adult education centre','die','noun','A2'),
      kw('der Teilnehmer','Teilnehmer','participant','der','noun','A2'),
      kw('der Fehler','Fehler','mistake','der','noun','A2'),
      kw('die Lehrerin','Lehrerin','female teacher','die','noun','A2'),
      kw('üben','üben','to practise',null,'verb','A2'),
      kw('helfen','helfen','to help',null,'verb','A2'),
      kw('sich freuen','sich freuen','to be pleased',null,'verb','A2'),
    ],
    quizQuestions: [
      qq('ps-a2-ed1-q1','María besucht einen Kurs an ___ Volkshochschule.','der',['die','dem'],'Dative after "an": "die Volkshochschule" → "der Volkshochschule".'),
      qq('ps-a2-ed1-q2','Sie macht ein paar ___.','Fehler',['Sätze','Worte'],'She makes a few mistakes.'),
      qq('ps-a2-ed1-q3','Die Lehrerin ___ ihr.','hilft',['sagt','zeigt'],'The teacher helps her — "helfen" + dative.'),
      qq('ps-a2-ed1-q4','Dein Deutsch wird immer ___.','besser',['gut','mehr'],'Comparative: "besser" = better.'),
      qq('ps-a2-ed1-q5','María freut ___ sehr.','sich',['ihr','ihr sich'],'Reflexive pronoun for "sich freuen".'),
    ],
    grammarNotes: [
      gn('ps-a2-ed1-g1','Dative verb "helfen"',
        'Die Lehrerin hilft ihr.',
        'The teacher helps her.',
        '"helfen" always takes the dative case for the person being helped. "sie" (she/her as nominative) → "ihr" (dative).',
        [{ de: 'Kannst du mir helfen?', native: 'Can you help me?' }]),
      gn('ps-a2-ed1-g2','Comparative adjectives',
        'Dein Deutsch wird immer besser.',
        'Your German is getting better and better.',
        'Comparative = adjective + "-er": gut → besser (irregular), schnell → schneller. "Immer + comparative" = increasingly.',
        [{ de: 'Er läuft immer schneller.', native: 'He runs faster and faster.' }]),
    ],
  },

  // ── B1 · Travel ──────────────────────────────────────────────────────────────
  {
    id: 'ps-b1-travel-001',
    title: 'Nachtzüge durch Europa',
    titleTranslation: 'Night Trains across Europe',
    level: 'B1', category: 'travel', isFiction: false, isPremium: false,
    wordCount: 92, estimatedReadMinutes: 3,
    topics: ['train', 'europe', 'overnight travel'],
    coverGradient: 'linear-gradient(135deg,#2D5A4E,#6BA08E)',
    bodyDe: 'Nachtzüge erleben in Europa eine Renaissance. Immer mehr Reisende entscheiden sich für den Zug statt des Flugzeugs, um lange Strecken zu überwinden. Der Vorteil ist offensichtlich: Man spart sich ein Hotelzimmer und wacht am Zielort ausgeruht auf. Die Österreichische Bundesbahn hat ihr Netz stark ausgebaut. Von Wien aus kann man heute direkt nach Paris, Amsterdam oder Hamburg fahren. Das Liegeabteil bietet sechs Betten und ein kleines Frühstück. Kritiker bemängeln jedoch die Preise: Ein Schlafwagen kostet oft mehr als ein Flug. Dennoch wächst die Nachfrage, besonders unter klimabewussten Reisenden.',
    bodyNative: 'Night trains are experiencing a renaissance in Europe. More and more travellers are choosing the train over the plane for long distances. The advantage is obvious: you save on a hotel room and wake up refreshed at your destination. Austrian Federal Railways has greatly expanded its network. From Vienna you can now travel directly to Paris, Amsterdam or Hamburg. The couchette offers six berths and a small breakfast. Critics point out the prices however: a sleeping car often costs more than a flight. Nevertheless demand is growing, especially among climate-conscious travellers.',
    sentences: [
      s(0,'Nachtzüge erleben in Europa eine Renaissance.','Night trains are experiencing a renaissance in Europe.'),
      s(1,'Immer mehr Reisende entscheiden sich für den Zug statt des Flugzeugs.','More and more travellers are choosing the train over the plane.'),
      s(2,'Der Vorteil ist offensichtlich: Man spart sich ein Hotelzimmer und wacht am Zielort ausgeruht auf.','The advantage is obvious: you save on a hotel room and wake up refreshed at your destination.'),
      s(3,'Die Österreichische Bundesbahn hat ihr Netz stark ausgebaut.','Austrian Federal Railways has greatly expanded its network.'),
      s(4,'Von Wien aus kann man heute direkt nach Paris, Amsterdam oder Hamburg fahren.','From Vienna you can now travel directly to Paris, Amsterdam or Hamburg.'),
      s(5,'Das Liegeabteil bietet sechs Betten und ein kleines Frühstück.','The couchette offers six berths and a small breakfast.'),
      s(6,'Kritiker bemängeln jedoch die Preise.','Critics point out the prices however.'),
      s(7,'Ein Schlafwagen kostet oft mehr als ein Flug.','A sleeping car often costs more than a flight.'),
      s(8,'Dennoch wächst die Nachfrage, besonders unter klimabewussten Reisenden.','Nevertheless demand is growing, especially among climate-conscious travellers.'),
    ],
    keywords: [
      kw('der Nachtzug','Nachtzug','night train','der','noun','B1'),
      kw('der Reisende','Reisende','traveller','der','noun','B1'),
      kw('der Vorteil','Vorteil','advantage','der','noun','B1'),
      kw('das Liegeabteil','Liegeabteil','couchette compartment','das','noun','B1'),
      kw('der Schlafwagen','Schlafwagen','sleeping car','der','noun','B1'),
      kw('die Nachfrage','Nachfrage','demand','die','noun','B1'),
      kw('klimabewusst','klimabewusst','climate-conscious',null,'adjective','B1'),
      kw('ausbauen','ausbauen','to expand / extend',null,'verb','B1'),
      kw('bemängeln','bemängeln','to criticise / find fault with',null,'verb','B1'),
    ],
    quizQuestions: [
      qq('ps-b1-t1-q1','Mehr Reisende entscheiden sich für den Zug statt ___ Flugzeugs.','des',['dem','das'],'Genitive after "statt": neuter article "das" → "des" in genitive.'),
      qq('ps-b1-t1-q2','Man ___ sich ein Hotelzimmer und wacht ausgeruht auf.','spart',['braucht','bucht'],'You save yourself a hotel room.'),
      qq('ps-b1-t1-q3','Das Liegeabteil ___ sechs Betten und ein Frühstück.','bietet',['hat','kostet'],'The couchette offers six berths.'),
      qq('ps-b1-t1-q4','Ein Schlafwagen kostet oft ___ als ein Flug.','mehr',['weniger','genauso'],'A sleeping car costs more than a flight.'),
      qq('ps-b1-t1-q5','Die Nachfrage wächst besonders unter ___ Reisenden.','klimabewussten',['neuen','alten'],'Among climate-conscious travellers — adjective ending in dative plural.'),
    ],
    grammarNotes: [
      gn('ps-b1-t1-g1','Genitive case with "statt"',
        'Statt des Flugzeugs nehmen sie den Zug.',
        'Instead of the plane they take the train.',
        '"statt" (instead of) governs the genitive case. Neuter "das Flugzeug" → genitive "des Flugzeugs". Masculine: "der Mann" → "des Mannes".',
        [{ de: 'Statt des Kaffees trinkt er Tee.', native: 'Instead of coffee he drinks tea.' }]),
      gn('ps-b1-t1-g2','Reflexive "sich entscheiden für"',
        'Reisende entscheiden sich für den Zug.',
        'Travellers choose the train.',
        '"sich entscheiden für" = to decide on / choose. The reflexive pronoun matches the subject. "für" takes the accusative.',
        [{ de: 'Ich entscheide mich für den Bus.', native: 'I choose the bus.' }]),
    ],
  },

  // ── B1 · Food & Culture ──────────────────────────────────────────────────────
  {
    id: 'ps-b1-food-001',
    title: 'Weihnachtsmärkte in Deutschland',
    titleTranslation: 'Christmas Markets in Germany',
    level: 'B1', category: 'food-culture', isFiction: false, isPremium: false,
    wordCount: 90, estimatedReadMinutes: 3,
    topics: ['christmas', 'traditions', 'markets'],
    coverGradient: 'linear-gradient(135deg,#7B2D00,#D4572A)',
    bodyDe: 'Jedes Jahr im Advent verwandeln sich die Innenstädte Deutschlands in festliche Weihnachtsmärkte. Der älteste und bekannteste ist der Christkindlesmarkt in Nürnberg, der seit dem 16. Jahrhundert stattfindet. Besucher schlendern zwischen Holzbuden und kaufen Lebkuchen, Glühwein und handgemachten Schmuck. Besonders beliebt sind die Holzfiguren aus dem Erzgebirge. Die Atmosphäre ist einzigartig: Lichterketten glänzen, Kinderchor singt Weihnachtslieder, und der Geruch von gebrannten Mandeln liegt in der Luft. Für viele Deutsche gehört ein Besuch auf dem Weihnachtsmarkt zur unverzichtbaren Vorweihnachtstradition.',
    bodyNative: 'Every year in Advent the inner cities of Germany are transformed into festive Christmas markets. The oldest and most famous is the Christkindlesmarkt in Nuremberg, which has taken place since the 16th century. Visitors stroll between wooden stalls and buy gingerbread, mulled wine and handmade jewellery. Particularly popular are the wooden figures from the Ore Mountains. The atmosphere is unique: fairy lights glitter, a children\'s choir sings Christmas carols, and the smell of roasted almonds hangs in the air. For many Germans a visit to the Christmas market is an indispensable pre-Christmas tradition.',
    sentences: [
      s(0,'Jedes Jahr im Advent verwandeln sich die Innenstädte Deutschlands in festliche Weihnachtsmärkte.','Every year in Advent the inner cities of Germany are transformed into festive Christmas markets.'),
      s(1,'Der älteste und bekannteste ist der Christkindlesmarkt in Nürnberg.','The oldest and most famous is the Christkindlesmarkt in Nuremberg.'),
      s(2,'Er findet seit dem 16. Jahrhundert statt.','It has taken place since the 16th century.'),
      s(3,'Besucher schlendern zwischen Holzbuden und kaufen Lebkuchen, Glühwein und handgemachten Schmuck.','Visitors stroll between wooden stalls and buy gingerbread, mulled wine and handmade jewellery.'),
      s(4,'Besonders beliebt sind die Holzfiguren aus dem Erzgebirge.','Particularly popular are the wooden figures from the Ore Mountains.'),
      s(5,'Lichterketten glänzen und ein Kinderchor singt Weihnachtslieder.','Fairy lights glitter and a children\'s choir sings Christmas carols.'),
      s(6,'Der Geruch von gebrannten Mandeln liegt in der Luft.','The smell of roasted almonds hangs in the air.'),
      s(7,'Für viele Deutsche gehört ein Besuch auf dem Weihnachtsmarkt zur unverzichtbaren Tradition.','For many Germans a visit to the Christmas market is an indispensable tradition.'),
    ],
    keywords: [
      kw('der Weihnachtsmarkt','Weihnachtsmarkt','Christmas market','der','noun','B1'),
      kw('der Glühwein','Glühwein','mulled wine','der','noun','B1'),
      kw('der Lebkuchen','Lebkuchen','gingerbread','der','noun','B1'),
      kw('die Lichterkette','Lichterkette','fairy lights (string)','die','noun','B1'),
      kw('die Mandel','Mandel','almond','die','noun','B1'),
      kw('schlendern','schlendern','to stroll',null,'verb','B1'),
      kw('unverzichtbar','unverzichtbar','indispensable',null,'adjective','B1'),
      kw('stattfinden','stattfinden','to take place',null,'verb','B1'),
    ],
    quizQuestions: [
      qq('ps-b1-f1-q1','Die Innenstädte ___ sich in Weihnachtsmärkte.','verwandeln',['ändern','bauen'],'They transform into Christmas markets — "sich verwandeln in".'),
      qq('ps-b1-f1-q2','Der Markt ___ seit dem 16. Jahrhundert statt.','findet',['hat','ist'],'Separable verb "stattfinden" — "statt" at end in present.'),
      qq('ps-b1-f1-q3','Besucher ___ zwischen Holzbuden.','schlendern',['gehen','laufen'],'Visitors stroll — "schlendern" implies leisurely walking.'),
      qq('ps-b1-f1-q4','Der Geruch von ___ Mandeln liegt in der Luft.','gebrannten',['süßen','frischen'],'The smell of roasted almonds — "gebrannt" = roasted/burnt.'),
      qq('ps-b1-f1-q5','Ein Besuch ___ zur Tradition.','gehört',['ist','macht'],'It belongs to tradition — "gehören zu" + dative.'),
    ],
    grammarNotes: [
      gn('ps-b1-f1-g1','Reflexive "sich verwandeln in"',
        'Die Innenstädte verwandeln sich in festliche Weihnachtsmärkte.',
        'The inner cities transform into festive Christmas markets.',
        '"sich verwandeln in" = to turn into. The reflexive pronoun matches the subject. "in" with destination/result takes accusative.',
        [{ de: 'Die Raupe verwandelt sich in einen Schmetterling.', native: 'The caterpillar transforms into a butterfly.' }]),
      gn('ps-b1-f1-g2','Superlatives',
        'Der älteste und bekannteste Markt ist in Nürnberg.',
        'The oldest and most famous market is in Nuremberg.',
        'German superlatives add "-ste" (after vowel: "-este"): alt → älteste, bekannt → bekannteste. Used attributively they take normal adjective endings.',
        [{ de: 'Das ist das schönste Lied.', native: 'That is the most beautiful song.' }]),
    ],
  },

  // ── B1 · Work & Career ───────────────────────────────────────────────────────
  {
    id: 'ps-b1-work-001',
    title: 'Das Vorstellungsgespräch',
    titleTranslation: 'The Job Interview',
    level: 'B1', category: 'work-career', isFiction: false, isPremium: false,
    wordCount: 88, estimatedReadMinutes: 3,
    topics: ['interview', 'job application', 'preparation'],
    coverGradient: 'linear-gradient(135deg,#1C3A5E,#2E86AB)',
    bodyDe: 'Nadia bereitet sich intensiv auf ihr Vorstellungsgespräch vor. Sie recherchiert das Unternehmen und überlegt sich Antworten auf typische Fragen. Am Tag des Gesprächs zieht sie sich professionell an und fährt früh los, um pünktlich zu sein. Im Büro wird sie von der Personalreferentin begrüßt. Das Gespräch beginnt gut: Die Interviewerin ist freundlich und stellt interessante Fragen über Nadias Berufserfahrung. Als sie nach den Gehaltsvorstellungen gefragt wird, nennt Nadia selbstbewusst eine Zahl. Am Ende der Stunde bedankt sie sich herzlich. Zwei Tage später bekommt sie die Zusage.',
    bodyNative: 'Nadia prepares intensively for her job interview. She researches the company and thinks of answers to typical questions. On the day of the interview she dresses professionally and sets off early to be on time. In the office she is greeted by the HR officer. The interview starts well: the interviewer is friendly and asks interesting questions about Nadia\'s professional experience. When asked about salary expectations she confidently names a figure. At the end of the hour she thanks them warmly. Two days later she receives the job offer.',
    sentences: [
      s(0,'Nadia bereitet sich intensiv auf ihr Vorstellungsgespräch vor.','Nadia prepares intensively for her job interview.'),
      s(1,'Sie recherchiert das Unternehmen und überlegt sich Antworten auf typische Fragen.','She researches the company and thinks of answers to typical questions.'),
      s(2,'Am Tag des Gesprächs zieht sie sich professionell an.','On the day of the interview she dresses professionally.'),
      s(3,'Sie fährt früh los, um pünktlich zu sein.','She sets off early to be on time.'),
      s(4,'Im Büro wird sie von der Personalreferentin begrüßt.','In the office she is greeted by the HR officer.'),
      s(5,'Die Interviewerin ist freundlich und stellt interessante Fragen.','The interviewer is friendly and asks interesting questions.'),
      s(6,'Als sie nach den Gehaltsvorstellungen gefragt wird, nennt Nadia selbstbewusst eine Zahl.','When asked about salary expectations she confidently names a figure.'),
      s(7,'Am Ende der Stunde bedankt sie sich herzlich.','At the end of the hour she thanks them warmly.'),
      s(8,'Zwei Tage später bekommt sie die Zusage.','Two days later she receives the job offer.'),
    ],
    keywords: [
      kw('das Vorstellungsgespräch','Vorstellungsgespräch','job interview','das','noun','B1'),
      kw('die Berufserfahrung','Berufserfahrung','professional experience','die','noun','B1'),
      kw('die Gehaltsvorstellung','Gehaltsvorstellung','salary expectation','die','noun','B1'),
      kw('die Zusage','Zusage','job offer / acceptance','die','noun','B1'),
      kw('selbstbewusst','selbstbewusst','confident',null,'adjective','B1'),
      kw('vorbereiten','vorbereiten','to prepare',null,'verb','B1'),
      kw('recherchieren','recherchieren','to research',null,'verb','B1'),
      kw('sich bedanken','sich bedanken','to thank',null,'verb','B1'),
    ],
    quizQuestions: [
      qq('ps-b1-w1-q1','Nadia bereitet sich ___ auf das Gespräch vor.','intensiv',['schnell','kurz'],'She prepares intensively.'),
      qq('ps-b1-w1-q2','Sie fährt früh los, ___ pünktlich zu sein.','um',['damit','weil'],'Purpose clause: "um … zu" + infinitive.'),
      qq('ps-b1-w1-q3','Im Büro ___ sie von der Personalreferentin begrüßt.','wird',['ist','hat'],'Passive voice: "werden" + past participle.'),
      qq('ps-b1-w1-q4','Nadia nennt ___ eine Zahl.','selbstbewusst',['nervös','leise'],'She confidently names a figure.'),
      qq('ps-b1-w1-q5','Zwei Tage später bekommt sie die ___.','Zusage',['Absage','Frage'],'She receives the job offer — "Zusage".'),
    ],
    grammarNotes: [
      gn('ps-b1-w1-g1','Purpose clause: "um … zu" + infinitive',
        'Sie fährt früh los, um pünktlich zu sein.',
        'She sets off early to be on time.',
        '"um … zu" expresses purpose (in order to). The infinitive goes to the end after "zu". The subject of both clauses must be the same.',
        [{ de: 'Er lernt Deutsch, um in Deutschland zu arbeiten.', native: 'He learns German in order to work in Germany.' }]),
      gn('ps-b1-w1-g2','Passive voice (Vorgangspassiv)',
        'Sie wird von der Personalreferentin begrüßt.',
        'She is greeted by the HR officer.',
        'Passive = "werden" (conjugated) + past participle at end. The agent (doer) is introduced by "von" + dative.',
        [{ de: 'Das Buch wird von ihr gelesen.', native: 'The book is being read by her.' }]),
    ],
  },

  // ── B1 · Nature ──────────────────────────────────────────────────────────────
  {
    id: 'ps-b1-nature-001',
    title: 'Wandern im Schwarzwald',
    titleTranslation: 'Hiking in the Black Forest',
    level: 'B1', category: 'nature-environment', isFiction: false, isPremium: false,
    wordCount: 88, estimatedReadMinutes: 3,
    topics: ['hiking', 'nature', 'forest'],
    coverGradient: 'linear-gradient(135deg,#1B4332,#40916C)',
    bodyDe: 'Der Schwarzwald im Südwesten Deutschlands ist ein Paradies für Wanderer. Auf über 23.000 Kilometern ausgeschilderten Wegen kann man durch dichte Wälder, an Seen vorbei und über sanfte Hügel wandern. Besonders beliebt ist der Westweg, der von Pforzheim bis Basel führt. Wer die Wanderung plant, sollte wetterfeste Kleidung und feste Schuhe mitnehmen. Im Wald begegnet man häufig Rehen und Wildschweinen. Die Schwarzwälder Küche bietet nach der Wanderung Stärkung: Schwarzwälder Kirschtorte und Vesper gehören dazu. Naturschutzgebiete machen fast dreißig Prozent des Waldes aus.',
    bodyNative: 'The Black Forest in south-west Germany is a paradise for hikers. On over 23,000 kilometres of marked trails you can hike through dense forests, past lakes and over gentle hills. Particularly popular is the Westweg, which runs from Pforzheim to Basel. Anyone planning the hike should bring weatherproof clothing and sturdy shoes. In the forest you frequently encounter deer and wild boar. Black Forest cuisine offers refreshment after the hike: Black Forest gateau and Vesper are included. Nature reserves make up almost thirty percent of the forest.',
    sentences: [
      s(0,'Der Schwarzwald im Südwesten Deutschlands ist ein Paradies für Wanderer.','The Black Forest in south-west Germany is a paradise for hikers.'),
      s(1,'Auf über 23.000 Kilometern ausgeschilderten Wegen kann man durch dichte Wälder wandern.','On over 23,000 kilometres of marked trails you can hike through dense forests.'),
      s(2,'Besonders beliebt ist der Westweg, der von Pforzheim bis Basel führt.','Particularly popular is the Westweg, which runs from Pforzheim to Basel.'),
      s(3,'Wer die Wanderung plant, sollte wetterfeste Kleidung und feste Schuhe mitnehmen.','Anyone planning the hike should bring weatherproof clothing and sturdy shoes.'),
      s(4,'Im Wald begegnet man häufig Rehen und Wildschweinen.','In the forest you frequently encounter deer and wild boar.'),
      s(5,'Die Schwarzwälder Küche bietet nach der Wanderung Stärkung.','Black Forest cuisine offers refreshment after the hike.'),
      s(6,'Schwarzwälder Kirschtorte und Vesper gehören dazu.','Black Forest gateau and Vesper are included.'),
      s(7,'Naturschutzgebiete machen fast dreißig Prozent des Waldes aus.','Nature reserves make up almost thirty percent of the forest.'),
    ],
    keywords: [
      kw('der Wanderer','Wanderer','hiker','der','noun','B1'),
      kw('der Weg','Weg','path / trail','der','noun','B1'),
      kw('das Reh','Reh','deer','das','noun','B1'),
      kw('das Wildschwein','Wildschwein','wild boar','das','noun','B1'),
      kw('das Naturschutzgebiet','Naturschutzgebiet','nature reserve','das','noun','B1'),
      kw('wetterfest','wetterfest','weatherproof',null,'adjective','B1'),
      kw('wandern','wandern','to hike',null,'verb','B1'),
      kw('ausmachen','ausmachen','to make up / constitute',null,'verb','B1'),
    ],
    quizQuestions: [
      qq('ps-b1-n1-q1','Der Schwarzwald ist ein Paradies für ___.','Wanderer',['Touristen','Sportler'],'It is a paradise for hikers.'),
      qq('ps-b1-n1-q2','Wer plant, ___ wetterfeste Kleidung mitnehmen.','sollte',['muss','kann'],'Modal "sollte" — should/ought to.'),
      qq('ps-b1-n1-q3','Im Wald ___ man häufig Rehen und Wildschweinen.','begegnet',['sieht','findet'],'You encounter deer and boar — "begegnen" + dative.'),
      qq('ps-b1-n1-q4','Naturschutzgebiete ___ fast dreißig Prozent aus.','machen',['sind','haben'],'Separable "ausmachen" — to make up / constitute.'),
      qq('ps-b1-n1-q5','Der Westweg ___ von Pforzheim bis Basel.','führt',['geht','fährt'],'The trail leads from Pforzheim to Basel.'),
    ],
    grammarNotes: [
      gn('ps-b1-n1-g1','Dative verb "begegnen"',
        'Im Wald begegnet man häufig Rehen.',
        'In the forest you frequently encounter deer.',
        '"begegnen" (to encounter/meet) takes the dative case for the person/thing encountered. "das Reh" (deer) → dative plural "den Rehen".',
        [{ de: 'Ich bin ihr auf der Straße begegnet.', native: 'I encountered her on the street.' }]),
      gn('ps-b1-n1-g2','Relative clause with "der" (masculine)',
        'Der Westweg, der von Pforzheim bis Basel führt.',
        'The Westweg, which runs from Pforzheim to Basel.',
        'The relative pronoun for a masculine nominative antecedent is "der". It introduces a subordinate clause with verb at end.',
        [{ de: 'Der Mann, der dort steht, ist mein Vater.', native: 'The man who is standing there is my father.' }]),
    ],
  },

  // ── B1 · Fiction ─────────────────────────────────────────────────────────────
  {
    id: 'ps-b1-fiction-001',
    title: 'Die Zeitreisende',
    titleTranslation: 'The Time Traveller',
    level: 'B1', category: 'fiction', isFiction: true, isPremium: false,
    wordCount: 94, estimatedReadMinutes: 3,
    topics: ['science fiction', 'time travel', 'mystery'],
    coverGradient: 'linear-gradient(135deg,#0D0D2B,#1A237E)',
    bodyDe: 'Sophie findet auf dem Dachboden ihrer Großmutter eine alte Taschenuhr. Als sie sie aufzieht, beginnt die Uhr seltsam zu leuchten. Plötzlich findet sie sich in einer fremden Stadt wieder — aber es ist Berlin, so wie es 1923 ausgesehen haben muss. Die Straßen sind belebt, die Menschen tragen alte Kleidung. Eine ältere Frau blickt sie neugierig an. "Sind Sie fremd hier?", fragt sie. Sophie zittert, nickt aber tapfer. Sie muss herausfinden, wie sie zurückkommt, bevor es zu spät ist. In ihrer Tasche findet sie zum Glück noch die Uhr.',
    bodyNative: 'Sophie finds an old pocket watch in her grandmother\'s attic. When she winds it up, the watch starts to glow strangely. Suddenly she finds herself in an unfamiliar city — but it is Berlin as it must have looked in 1923. The streets are busy, the people wear old clothes. An older woman looks at her curiously. "Are you a stranger here?" she asks. Sophie trembles but nods bravely. She has to find out how to get back before it is too late. Fortunately she still has the watch in her pocket.',
    sentences: [
      s(0,'Sophie findet auf dem Dachboden ihrer Großmutter eine alte Taschenuhr.','Sophie finds an old pocket watch in her grandmother\'s attic.'),
      s(1,'Als sie sie aufzieht, beginnt die Uhr seltsam zu leuchten.','When she winds it up, the watch starts to glow strangely.'),
      s(2,'Plötzlich findet sie sich in einer fremden Stadt wieder.','Suddenly she finds herself in an unfamiliar city.'),
      s(3,'Es ist Berlin, so wie es 1923 ausgesehen haben muss.','It is Berlin as it must have looked in 1923.'),
      s(4,'Die Straßen sind belebt, die Menschen tragen alte Kleidung.','The streets are busy, the people wear old clothes.'),
      s(5,'Eine ältere Frau blickt sie neugierig an.','An older woman looks at her curiously.'),
      s(6,'"Sind Sie fremd hier?", fragt sie.','"Are you a stranger here?" she asks.'),
      s(7,'Sophie zittert, nickt aber tapfer.','Sophie trembles but nods bravely.'),
      s(8,'Sie muss herausfinden, wie sie zurückkommt, bevor es zu spät ist.','She has to find out how to get back before it is too late.'),
      s(9,'In ihrer Tasche findet sie zum Glück noch die Uhr.','Fortunately she still has the watch in her pocket.'),
    ],
    keywords: [
      kw('die Taschenuhr','Taschenuhr','pocket watch','die','noun','B1'),
      kw('der Dachboden','Dachboden','attic','der','noun','B1'),
      kw('aufziehen','aufziehen','to wind up (a watch)',null,'verb','B1'),
      kw('leuchten','leuchten','to glow / shine',null,'verb','B1'),
      kw('zittern','zittern','to tremble',null,'verb','B1'),
      kw('tapfer','tapfer','brave',null,'adjective','B1'),
      kw('herausfinden','herausfinden','to find out',null,'verb','B1'),
      kw('belebt','belebt','busy / lively',null,'adjective','B1'),
    ],
    quizQuestions: [
      qq('ps-b1-fi1-q1','Als sie die Uhr ___, beginnt sie zu leuchten.','aufzieht',['öffnet','dreht'],'She winds up the watch — "aufziehen".'),
      qq('ps-b1-fi1-q2','Sophie findet sich in einer ___ Stadt wieder.','fremden',['alten','neuen'],'She finds herself in an unfamiliar city.'),
      qq('ps-b1-fi1-q3','Es ist Berlin, so wie es 1923 ausgesehen ___ muss.','haben',['sein','werden'],'Modal perfect: "ausgesehen haben muss" = must have looked.'),
      qq('ps-b1-fi1-q4','Sophie zittert, nickt aber ___.','tapfer',['schnell','laut'],'She trembles but nods bravely.'),
      qq('ps-b1-fi1-q5','Sie muss herausfinden, ___ sie zurückkommt.','wie',['wann','ob'],'She has to find out how to get back.'),
    ],
    grammarNotes: [
      gn('ps-b1-fi1-g1','Temporal conjunction "als"',
        'Als sie die Uhr aufzieht, beginnt sie zu leuchten.',
        'When she winds it up, the watch starts to glow.',
        '"Als" introduces a one-time event in the past or a single point in time. The verb goes to the end of the "als" clause.',
        [{ de: 'Als er ankam, war sie schon weg.', native: 'When he arrived, she was already gone.' }]),
      gn('ps-b1-fi1-g2','Modal perfect: Konjunktiv II',
        'So wie es 1923 ausgesehen haben muss.',
        'As it must have looked in 1923.',
        'Modal + perfect infinitive: "müssen" + perfect infinitive expresses logical deduction about the past. Structure: modal verb + "haben/sein" + past participle.',
        [{ de: 'Er muss das gewusst haben.', native: 'He must have known that.' }]),
    ],
  },

  // ── B2 · Technology ──────────────────────────────────────────────────────────
  {
    id: 'ps-b2-tech-001',
    title: 'Künstliche Intelligenz im Alltag',
    titleTranslation: 'Artificial Intelligence in Everyday Life',
    level: 'B2', category: 'technology', isFiction: false, isPremium: true,
    wordCount: 102, estimatedReadMinutes: 4,
    topics: ['AI', 'technology', 'society'],
    coverGradient: 'linear-gradient(135deg,#0A0A23,#1565C0)',
    bodyDe: 'Künstliche Intelligenz hat sich in den letzten Jahren rasant entwickelt und ist mittlerweile ein fester Bestandteil unseres Alltags geworden. Sprachassistenten helfen uns beim Planen des Tages, Algorithmen kuratieren unsere Nachrichten, und Empfehlungssysteme schlagen uns Musik und Filme vor. Doch diese Entwicklung wirft auch ernsthafte Fragen auf. Kritiker warnen vor der sogenannten Filterbubble: Wenn Algorithmen nur zeigen, was wir sehen wollen, verengt sich unser Weltbild. Datenschützer mahnen, dass persönliche Daten oft ohne ausreichende Transparenz gesammelt werden. Gleichzeitig birgt KI enormes Potenzial für Medizin, Klimaforschung und Bildung. Die Herausforderung besteht darin, den technologischen Fortschritt so zu gestalten, dass er der Gesellschaft als Ganzes nutzt.',
    bodyNative: 'Artificial intelligence has developed rapidly in recent years and has become a permanent part of our everyday lives. Voice assistants help us plan our day, algorithms curate our news, and recommendation systems suggest music and films. But this development also raises serious questions. Critics warn of the so-called filter bubble: when algorithms only show what we want to see, our worldview narrows. Data protection advocates caution that personal data is often collected without sufficient transparency. At the same time AI holds enormous potential for medicine, climate research and education. The challenge is to shape technological progress in a way that benefits society as a whole.',
    sentences: [
      s(0,'Künstliche Intelligenz hat sich in den letzten Jahren rasant entwickelt.','Artificial intelligence has developed rapidly in recent years.'),
      s(1,'Sie ist mittlerweile ein fester Bestandteil unseres Alltags geworden.','It has become a permanent part of our everyday lives.'),
      s(2,'Sprachassistenten helfen uns beim Planen des Tages.','Voice assistants help us plan our day.'),
      s(3,'Algorithmen kuratieren unsere Nachrichten und Empfehlungssysteme schlagen uns Musik vor.','Algorithms curate our news and recommendation systems suggest music to us.'),
      s(4,'Kritiker warnen vor der sogenannten Filterbubble.','Critics warn of the so-called filter bubble.'),
      s(5,'Wenn Algorithmen nur zeigen, was wir sehen wollen, verengt sich unser Weltbild.','When algorithms only show what we want to see, our worldview narrows.'),
      s(6,'Datenschützer mahnen, dass Daten oft ohne ausreichende Transparenz gesammelt werden.','Data protection advocates caution that data is often collected without sufficient transparency.'),
      s(7,'Gleichzeitig birgt KI enormes Potenzial für Medizin und Bildung.','At the same time AI holds enormous potential for medicine and education.'),
      s(8,'Die Herausforderung besteht darin, den Fortschritt so zu gestalten, dass er der Gesellschaft nutzt.','The challenge is to shape progress so that it benefits society.'),
    ],
    keywords: [
      kw('der Bestandteil','Bestandteil','component / part','der','noun','B2'),
      kw('der Algorithmus','Algorithmus','algorithm','der','noun','B2'),
      kw('die Filterbubble','Filterbubble','filter bubble','die','noun','B2'),
      kw('der Datenschützer','Datenschützer','data protection advocate','der','noun','B2'),
      kw('das Potenzial','Potenzial','potential','das','noun','B2'),
      kw('mahnen','mahnen','to caution / warn',null,'verb','B2'),
      kw('verengen','verengen','to narrow',null,'verb','B2'),
      kw('gestalten','gestalten','to shape / design',null,'verb','B2'),
      kw('bergen','bergen','to hold / contain (a risk)',null,'verb','B2'),
    ],
    quizQuestions: [
      qq('ps-b2-t1-q1','KI ist ___ ein fester Bestandteil unseres Alltags.','mittlerweile',['bereits','noch'],'It has by now become a fixed part of everyday life.'),
      qq('ps-b2-t1-q2','Kritiker warnen ___ der Filterbubble.','vor',['gegen','über'],'Warning about something: "warnen vor" + dative.'),
      qq('ps-b2-t1-q3','Wenn Algorithmen nur zeigen was wir wollen, ___ sich unser Weltbild.','verengt',['ändert','wächst'],'Our worldview narrows — "sich verengen".'),
      qq('ps-b2-t1-q4','Daten werden oft ___ ausreichende Transparenz gesammelt.','ohne',['mit','trotz'],'Without sufficient transparency — "ohne" + accusative.'),
      qq('ps-b2-t1-q5','Die Herausforderung besteht ___, den Fortschritt zu gestalten.','darin',['daran','dabei'],'The challenge consists in shaping progress — "bestehen darin".'),
    ],
    grammarNotes: [
      gn('ps-b2-t1-g1','Extended participial phrase',
        'Ein fester Bestandteil unseres Alltags.',
        'A permanent part of our everyday lives.',
        'Genitive attributes chain in German: "unseres Alltags" = of our everyday life. "unser" (possessive) in genitive: masculine/neuter "-es", feminine/plural "-er".',
        [{ de: 'Das Auto meines Vaters.', native: 'My father\'s car.' }]),
      gn('ps-b2-t1-g2','Consecutive clause: "so … dass"',
        'Den Fortschritt so gestalten, dass er der Gesellschaft nutzt.',
        'To shape progress so that it benefits society.',
        '"so … dass" introduces a result clause. The first clause contains "so" + adjective/adverb; "dass" introduces the consequence with verb at end.',
        [{ de: 'Er spricht so leise, dass ich ihn nicht verstehe.', native: 'He speaks so quietly that I don\'t understand him.' }]),
    ],
  },

  // ── B2 · Work & Career ───────────────────────────────────────────────────────
  {
    id: 'ps-b2-work-001',
    title: 'Verhandlungen führen',
    titleTranslation: 'Conducting Negotiations',
    level: 'B2', category: 'work-career', isFiction: false, isPremium: true,
    wordCount: 98, estimatedReadMinutes: 4,
    topics: ['negotiation', 'business', 'strategy'],
    coverGradient: 'linear-gradient(135deg,#1A1A2E,#16213E)',
    bodyDe: 'Erfolgreiche Verhandlungen erfordern gründliche Vorbereitung, emotionale Intelligenz und die Fähigkeit, die Perspektive des Gegenübers einzunehmen. Im Deutschen Unternehmensumfeld sind direkte, sachliche Kommunikation und Verlässlichkeit besonders geschätzt. Bevor man in eine Verhandlung geht, sollte man die eigene Verhandlungsposition klar definieren: Was ist das Ziel? Welche Zugeständnisse ist man bereit zu machen? Während der Verhandlung ist aktives Zuhören entscheidend. Wer paraphrasiert, was die andere Seite gesagt hat, signalisiert Respekt und gewinnt Zeit zum Nachdenken. Kompromisse sollten als Erfolg für beide Seiten kommuniziert werden, nicht als Niederlage. Nach Abschluss einer Einigung ist ein schriftliches Protokoll unbedingt empfehlenswert.',
    bodyNative: 'Successful negotiations require thorough preparation, emotional intelligence and the ability to take the other party\'s perspective. In the German business environment direct, factual communication and reliability are particularly valued. Before entering a negotiation one should clearly define one\'s own negotiating position: What is the goal? What concessions is one prepared to make? During the negotiation active listening is crucial. Whoever paraphrases what the other side has said signals respect and gains time to think. Compromises should be communicated as a success for both sides, not as a defeat. After reaching an agreement a written minute is strongly recommended.',
    sentences: [
      s(0,'Erfolgreiche Verhandlungen erfordern gründliche Vorbereitung und emotionale Intelligenz.','Successful negotiations require thorough preparation and emotional intelligence.'),
      s(1,'Im deutschen Unternehmensumfeld sind direkte Kommunikation und Verlässlichkeit besonders geschätzt.','In the German business environment direct communication and reliability are particularly valued.'),
      s(2,'Bevor man in eine Verhandlung geht, sollte man die eigene Position klar definieren.','Before entering a negotiation one should clearly define one\'s own position.'),
      s(3,'Was ist das Ziel? Welche Zugeständnisse ist man bereit zu machen?','What is the goal? What concessions is one prepared to make?'),
      s(4,'Während der Verhandlung ist aktives Zuhören entscheidend.','During the negotiation active listening is crucial.'),
      s(5,'Wer paraphrasiert, was die andere Seite gesagt hat, signalisiert Respekt.','Whoever paraphrases what the other side said signals respect.'),
      s(6,'Kompromisse sollten als Erfolg für beide Seiten kommuniziert werden.','Compromises should be communicated as a success for both sides.'),
      s(7,'Nach Abschluss einer Einigung ist ein schriftliches Protokoll empfehlenswert.','After reaching an agreement a written minute is recommended.'),
    ],
    keywords: [
      kw('die Verhandlung','Verhandlung','negotiation','die','noun','B2'),
      kw('das Zugeständnis','Zugeständnis','concession','das','noun','B2'),
      kw('die Verlässlichkeit','Verlässlichkeit','reliability','die','noun','B2'),
      kw('das Protokoll','Protokoll','minutes / record','das','noun','B2'),
      kw('paraphrasieren','paraphrasieren','to paraphrase',null,'verb','B2'),
      kw('entscheidend','entscheidend','crucial',null,'adjective','B2'),
      kw('erfordern','erfordern','to require',null,'verb','B2'),
      kw('empfehlenswert','empfehlenswert','recommendable',null,'adjective','B2'),
    ],
    quizQuestions: [
      qq('ps-b2-w1-q1','Verhandlungen ___ gründliche Vorbereitung.','erfordern',['brauchen','wollen'],'To require — "erfordern".'),
      qq('ps-b2-w1-q2','Bevor man verhandelt, sollte man die Position klar ___.','definieren',['klären','sagen'],'One should clearly define the position.'),
      qq('ps-b2-w1-q3','Aktives Zuhören ist ___.','entscheidend',['wichtig','nötig'],'Active listening is crucial — "entscheidend".'),
      qq('ps-b2-w1-q4','Kompromisse sollten als Erfolg ___ kommuniziert werden.','kommuniziert',['gesagt','gemacht'],'Passive infinitive: "kommuniziert werden".'),
      qq('ps-b2-w1-q5','Ein schriftliches Protokoll ist ___.','empfehlenswert',['nötig','wichtig'],'A written minute is recommendable.'),
    ],
    grammarNotes: [
      gn('ps-b2-w1-g1','Infinitive clause with "bereit sein zu"',
        'Welche Zugeständnisse ist man bereit zu machen?',
        'What concessions is one prepared to make?',
        '"bereit sein zu" + infinitive = to be prepared/willing to do something. The infinitive goes to the very end after "zu".',
        [{ de: 'Ich bin bereit zu helfen.', native: 'I am prepared to help.' }]),
      gn('ps-b2-w1-g2','Modal passive infinitive',
        'Kompromisse sollten als Erfolg kommuniziert werden.',
        'Compromises should be communicated as a success.',
        'Modal verb + passive infinitive: "sollten" + past participle + "werden". The agent is omitted when unimportant.',
        [{ de: 'Das muss sofort erledigt werden.', native: 'That must be done immediately.' }]),
    ],
  },

  // ── B2 · Daily Life ──────────────────────────────────────────────────────────
  {
    id: 'ps-b2-daily-001',
    title: 'WG-Leben in München',
    titleTranslation: 'Shared Flat Life in Munich',
    level: 'B2', category: 'daily-life', isFiction: false, isPremium: false,
    wordCount: 96, estimatedReadMinutes: 3,
    topics: ['flatshare', 'city life', 'Munich'],
    coverGradient: 'linear-gradient(135deg,#4A1942,#9B2335)',
    bodyDe: 'Das Wohnen in einer Wohngemeinschaft ist für viele Studenten und Berufseinsteiger in München die einzige erschwingliche Möglichkeit, in der Stadt zu leben. Die Mietpreise für Einzelapartments haben in den letzten Jahren derart angezogen, dass selbst gut verdienende Berufseinsteiger kaum eine Chance haben, alleine zu wohnen. Eine WG bietet jedoch nicht nur finanzielle Vorteile: Man lernt Menschen aus anderen Kulturen kennen, teilt Verantwortung im Haushalt und hat immer Gesellschaft. Konflikte entstehen oft wegen unterschiedlicher Vorstellungen von Sauberkeit oder Nachtruhe. Wer klare Absprachen trifft und Rücksicht nimmt, macht die besten Erfahrungen. München hat eine lebhafte WG-Kultur mit einer eigenen Community auf Plattformen wie WG-Gesucht.',
    bodyNative: 'Living in a shared flat is for many students and young professionals in Munich the only affordable option for living in the city. Rental prices for individual apartments have risen so sharply in recent years that even well-earning young professionals have little chance of living alone. A shared flat offers more than just financial advantages however: you get to know people from other cultures, share household responsibilities and always have company. Conflicts often arise because of differing ideas about cleanliness or quiet hours at night. Those who make clear agreements and show consideration have the best experience. Munich has a vibrant shared-flat culture with its own community on platforms like WG-Gesucht.',
    sentences: [
      s(0,'Das Wohnen in einer WG ist für viele die einzige erschwingliche Möglichkeit in München.','Living in a shared flat is for many the only affordable option in Munich.'),
      s(1,'Die Mietpreise haben in den letzten Jahren derart angezogen, dass Einzelapartments kaum erschwinglich sind.','Rental prices have risen so sharply that individual apartments are barely affordable.'),
      s(2,'Eine WG bietet nicht nur finanzielle Vorteile.','A shared flat offers more than just financial advantages.'),
      s(3,'Man lernt Menschen aus anderen Kulturen kennen und teilt Verantwortung im Haushalt.','You get to know people from other cultures and share household responsibilities.'),
      s(4,'Konflikte entstehen oft wegen unterschiedlicher Vorstellungen von Sauberkeit.','Conflicts often arise because of differing ideas about cleanliness.'),
      s(5,'Wer klare Absprachen trifft und Rücksicht nimmt, macht die besten Erfahrungen.','Those who make clear agreements and show consideration have the best experience.'),
      s(6,'München hat eine lebhafte WG-Kultur mit einer eigenen Community.','Munich has a vibrant shared-flat culture with its own community.'),
    ],
    keywords: [
      kw('die Wohngemeinschaft','Wohngemeinschaft','shared flat','die','noun','B2'),
      kw('die Mietpreise','Mietpreise','rental prices','die','noun','B2'),
      kw('die Absprache','Absprache','agreement / arrangement','die','noun','B2'),
      kw('die Rücksicht','Rücksicht','consideration / regard','die','noun','B2'),
      kw('erschwinglich','erschwinglich','affordable',null,'adjective','B2'),
      kw('anziehen','anziehen','to rise sharply (prices)',null,'verb','B2'),
      kw('entstehen','entstehen','to arise / emerge',null,'verb','B2'),
      kw('lebhaft','lebhaft','vibrant / lively',null,'adjective','B2'),
    ],
    quizQuestions: [
      qq('ps-b2-d1-q1','Es ist die einzige ___ Möglichkeit in München.','erschwingliche',['gute','freie'],'The only affordable option.'),
      qq('ps-b2-d1-q2','Die Mietpreise haben derart ___, dass Apartments kaum erschwinglich sind.','angezogen',['gestiegen','zugenommen'],'Prices rose sharply — "anziehen" used for price increases.'),
      qq('ps-b2-d1-q3','Konflikte entstehen ___ unterschiedlicher Vorstellungen.','wegen',['durch','von'],'Causal preposition "wegen" + genitive.'),
      qq('ps-b2-d1-q4','Wer Rücksicht ___, macht die besten Erfahrungen.','nimmt',['hat','gibt'],'To show consideration — "Rücksicht nehmen".'),
      qq('ps-b2-d1-q5','München hat eine ___ WG-Kultur.','lebhafte',['große','aktive'],'A vibrant shared-flat culture — "lebhaft".'),
    ],
    grammarNotes: [
      gn('ps-b2-d1-g1','Causal preposition "wegen" + genitive',
        'Konflikte entstehen wegen unterschiedlicher Vorstellungen.',
        'Conflicts arise because of differing ideas.',
        '"wegen" (because of) governs the genitive. "unterschiedliche Vorstellungen" → genitive plural: "unterschiedlicher Vorstellungen".',
        [{ de: 'Wegen des Wetters bleiben wir zu Hause.', native: 'Because of the weather we stay at home.' }]),
      gn('ps-b2-d1-g2','Consecutive "derart … dass"',
        'Die Mietpreise haben derart angezogen, dass Einzelapartments kaum erschwinglich sind.',
        'Rental prices have risen so sharply that individual apartments are barely affordable.',
        '"derart … dass" = so much that. It introduces a result clause. "derart" modifies the degree of the action.',
        [{ de: 'Er hat derart laut geschrien, dass alle erschrocken sind.', native: 'He shouted so loudly that everyone was startled.' }]),
    ],
  },

  // ── B2 · Fiction ─────────────────────────────────────────────────────────────
  {
    id: 'ps-b2-fiction-001',
    title: 'Der letzte Zug nach Wien',
    titleTranslation: 'The Last Train to Vienna',
    level: 'B2', category: 'fiction', isFiction: true, isPremium: true,
    wordCount: 108, estimatedReadMinutes: 4,
    topics: ['thriller', 'train', 'mystery'],
    coverGradient: 'linear-gradient(135deg,#1A0A2E,#4A1942)',
    bodyDe: 'Der letzte Zug nach Wien verlässt München Hauptbahnhof um 23:47 Uhr. Kommissarin Haller betritt das leere Abteil mit einem unguten Gefühl. Ihr Kollege hatte sie kurz zuvor angerufen: Jemand habe einen verdächtigen Koffer im Zug zurückgelassen. Sie geht den Gang entlang, die Hand am Dienstausweis. Im vorletzten Wagen entdeckt sie einen älteren Herrn, der tief schläft — und neben ihm einen schwarzen Koffer. Als sie ihn ansprechen will, öffnet sich am anderen Ende des Waggons eine Tür. Eine junge Frau tritt ein, sieht Haller, und erstarrt. In diesem Moment fährt der Zug in einen Tunnel. Die Lichter erlöschen.',
    bodyNative: 'The last train to Vienna leaves Munich Central Station at 23:47. Detective Haller enters the empty compartment with a bad feeling. Her colleague had called her shortly before: someone had left a suspicious suitcase on the train. She walks along the corridor, her hand on her badge. In the second-to-last carriage she discovers an older gentleman sleeping deeply — and next to him a black suitcase. Just as she is about to address him, a door opens at the other end of the carriage. A young woman enters, sees Haller, and freezes. At that moment the train enters a tunnel. The lights go out.',
    sentences: [
      s(0,'Der letzte Zug nach Wien verlässt München Hauptbahnhof um 23:47 Uhr.','The last train to Vienna leaves Munich Central Station at 23:47.'),
      s(1,'Kommissarin Haller betritt das leere Abteil mit einem unguten Gefühl.','Detective Haller enters the empty compartment with a bad feeling.'),
      s(2,'Ihr Kollege hatte sie kurz zuvor angerufen.','Her colleague had called her shortly before.'),
      s(3,'Jemand habe einen verdächtigen Koffer im Zug zurückgelassen.','Someone had left a suspicious suitcase on the train.'),
      s(4,'Sie geht den Gang entlang, die Hand am Dienstausweis.','She walks along the corridor, her hand on her badge.'),
      s(5,'Im vorletzten Wagen entdeckt sie einen älteren Herrn, der tief schläft.','In the second-to-last carriage she discovers an older gentleman sleeping deeply.'),
      s(6,'Neben ihm liegt ein schwarzer Koffer.','Next to him lies a black suitcase.'),
      s(7,'Als sie ihn ansprechen will, öffnet sich am anderen Ende eine Tür.','Just as she is about to address him, a door opens at the other end.'),
      s(8,'Eine junge Frau tritt ein, sieht Haller, und erstarrt.','A young woman enters, sees Haller, and freezes.'),
      s(9,'In diesem Moment fährt der Zug in einen Tunnel. Die Lichter erlöschen.','At that moment the train enters a tunnel. The lights go out.'),
    ],
    keywords: [
      kw('die Kommissarin','Kommissarin','female detective / commissioner','die','noun','B2'),
      kw('das Abteil','Abteil','compartment','das','noun','B2'),
      kw('der Koffer','Koffer','suitcase','der','noun','B2'),
      kw('der Gang','Gang','corridor','der','noun','B2'),
      kw('der Dienstausweis','Dienstausweis','badge / ID card','der','noun','B2'),
      kw('erstarren','erstarren','to freeze / be rooted to spot',null,'verb','B2'),
      kw('erlöschen','erlöschen','to go out (lights)',null,'verb','B2'),
      kw('verdächtig','verdächtig','suspicious',null,'adjective','B2'),
      kw('ansprechen','ansprechen','to address / approach',null,'verb','B2'),
    ],
    quizQuestions: [
      qq('ps-b2-fi1-q1','Haller betritt das Abteil mit einem ___ Gefühl.','unguten',['schlechten','bösen'],'With a bad/uneasy feeling — "ungut".'),
      qq('ps-b2-fi1-q2','Ihr Kollege ___ sie kurz zuvor angerufen.','hatte',['hat','war'],'Pluperfect: "hatte … angerufen" = had called.'),
      qq('ps-b2-fi1-q3','Jemand ___ einen verdächtigen Koffer zurückgelassen.','habe',['hatte','hat'],'Konjunktiv I in reported speech: "habe … zurückgelassen".'),
      qq('ps-b2-fi1-q4','Als sie ihn ansprechen ___, öffnet sich eine Tür.','will',['wollte','würde'],'Present tense "will" — just as she is about to.'),
      qq('ps-b2-fi1-q5','Die Lichter ___.','erlöschen',['ausgehen','schalten'],'The lights go out — "erlöschen" (literary, intransitive).'),
    ],
    grammarNotes: [
      gn('ps-b2-fi1-g1','Pluperfect (Plusquamperfekt)',
        'Ihr Kollege hatte sie kurz zuvor angerufen.',
        'Her colleague had called her shortly before.',
        'Pluperfect = "hatte/war" (past) + past participle. Used for events that happened before another past event. "hatte angerufen" = had called.',
        [{ de: 'Nachdem er gegessen hatte, ging er schlafen.', native: 'After he had eaten, he went to sleep.' }]),
      gn('ps-b2-fi1-g2','Konjunktiv I (indirect speech)',
        'Jemand habe einen Koffer zurückgelassen.',
        'Someone had left a suitcase (reportedly).',
        'Konjunktiv I is used in indirect/reported speech. "hat … gelassen" (direct) → "habe … gelassen" (indirect). Signals the speaker is not confirming the statement.',
        [{ de: 'Er sagte, er sei krank.', native: 'He said he was ill.' }]),
    ],
  },

  // ── B2 · Nature ──────────────────────────────────────────────────────────────
  {
    id: 'ps-b2-nature-001',
    title: 'Klimawandel und Nachhaltigkeit',
    titleTranslation: 'Climate Change and Sustainability',
    level: 'B2', category: 'nature-environment', isFiction: false, isPremium: false,
    wordCount: 105, estimatedReadMinutes: 4,
    topics: ['climate', 'environment', 'sustainability'],
    coverGradient: 'linear-gradient(135deg,#0D4F2E,#1B8A4E)',
    bodyDe: 'Der Klimawandel stellt eine der größten Herausforderungen unserer Zeit dar. Wissenschaftliche Studien belegen, dass die Durchschnittstemperatur der Erde seit der Industrialisierung um etwa 1,2 Grad Celsius gestiegen ist. Die Folgen sind bereits spürbar: häufigere Extremwetterereignisse, steigende Meeresspiegel und der Rückzug von Gletschern. Um die Erderwärmung zu begrenzen, haben 197 Länder das Pariser Abkommen unterzeichnet, das eine Begrenzung auf 1,5 Grad anstrebt. Deutschland hat sich verpflichtet, bis 2045 klimaneutral zu sein. Nachhaltigkeit bedeutet jedoch mehr als Energiepolitik: Es geht um veränderte Konsumgewohnheiten, nachhaltige Landwirtschaft und den Erhalt der Artenvielfalt. Jede Entscheidung im Alltag — was wir essen, wie wir reisen, was wir kaufen — hat einen ökologischen Fußabdruck.',
    bodyNative: 'Climate change is one of the greatest challenges of our time. Scientific studies show that the average temperature of the earth has risen by about 1.2 degrees Celsius since industrialisation. The consequences are already noticeable: more frequent extreme weather events, rising sea levels and the retreat of glaciers. To limit global warming 197 countries have signed the Paris Agreement, which aims for a limit of 1.5 degrees. Germany has committed to being climate-neutral by 2045. Sustainability means more than energy policy however: it is about changed consumption habits, sustainable agriculture and the preservation of biodiversity. Every everyday decision — what we eat, how we travel, what we buy — has an ecological footprint.',
    sentences: [
      s(0,'Der Klimawandel stellt eine der größten Herausforderungen unserer Zeit dar.','Climate change is one of the greatest challenges of our time.'),
      s(1,'Die Durchschnittstemperatur ist seit der Industrialisierung um 1,2 Grad gestiegen.','The average temperature has risen by 1.2 degrees since industrialisation.'),
      s(2,'Die Folgen sind spürbar: häufigere Extremwetterereignisse und steigende Meeresspiegel.','The consequences are noticeable: more frequent extreme weather events and rising sea levels.'),
      s(3,'197 Länder haben das Pariser Abkommen unterzeichnet.','197 countries have signed the Paris Agreement.'),
      s(4,'Deutschland hat sich verpflichtet, bis 2045 klimaneutral zu sein.','Germany has committed to being climate-neutral by 2045.'),
      s(5,'Nachhaltigkeit bedeutet mehr als Energiepolitik.','Sustainability means more than energy policy.'),
      s(6,'Es geht um Konsumgewohnheiten, nachhaltige Landwirtschaft und den Erhalt der Artenvielfalt.','It is about consumption habits, sustainable agriculture and the preservation of biodiversity.'),
      s(7,'Jede Entscheidung im Alltag hat einen ökologischen Fußabdruck.','Every everyday decision has an ecological footprint.'),
    ],
    keywords: [
      kw('der Klimawandel','Klimawandel','climate change','der','noun','B2'),
      kw('die Nachhaltigkeit','Nachhaltigkeit','sustainability','die','noun','B2'),
      kw('der Meeresspiegel','Meeresspiegel','sea level','der','noun','B2'),
      kw('der Gletscher','Gletscher','glacier','der','noun','B2'),
      kw('die Artenvielfalt','Artenvielfalt','biodiversity','die','noun','B2'),
      kw('der Fußabdruck','Fußabdruck','footprint','der','noun','B2'),
      kw('klimaneutral','klimaneutral','climate-neutral',null,'adjective','B2'),
      kw('unterzeichnen','unterzeichnen','to sign',null,'verb','B2'),
      kw('sich verpflichten','sich verpflichten','to commit / pledge',null,'verb','B2'),
    ],
    quizQuestions: [
      qq('ps-b2-n1-q1','Der Klimawandel stellt eine große ___ dar.','Herausforderung',['Aufgabe','Gefahr'],'Separable "darstellen" = to represent/constitute.'),
      qq('ps-b2-n1-q2','Die Temperatur ist ___ der Industrialisierung gestiegen.','seit',['nach','vor'],'Since industrialisation — temporal "seit" + dative.'),
      qq('ps-b2-n1-q3','Deutschland hat sich ___, klimaneutral zu sein.','verpflichtet',['entschieden','bemüht'],'Germany committed — "sich verpflichten".'),
      qq('ps-b2-n1-q4','Nachhaltigkeit ___ mehr als Energiepolitik.','bedeutet',['ist','heißt'],'Sustainability means more — "bedeuten".'),
      qq('ps-b2-n1-q5','Jede Entscheidung hat einen ___ Fußabdruck.','ökologischen',['großen','kleinen'],'An ecological footprint — adjective ending accusative masculine.'),
    ],
    grammarNotes: [
      gn('ps-b2-n1-g1','Separable verb "darstellen"',
        'Der Klimawandel stellt eine große Herausforderung dar.',
        'Climate change is a great challenge.',
        '"darstellen" = to represent/constitute. Separable: "stellt … dar". In subordinate clauses the full verb moves to the end: "…, dass er eine Herausforderung darstellt."',
        [{ de: 'Das stellt ein Problem dar.', native: 'That represents a problem.' }]),
      gn('ps-b2-n1-g2','Verpflichten + zu + infinitive',
        'Deutschland hat sich verpflichtet, klimaneutral zu sein.',
        'Germany has committed to being climate-neutral.',
        '"sich verpflichten" + "zu" + infinitive. The infinitive clause is separated by a comma. "zu" comes directly before the infinitive.',
        [{ de: 'Wir haben uns verpflichtet, das Projekt fertigzustellen.', native: 'We committed to completing the project.' }]),
    ],
  },

];
