import type { AdminImportCollectionJsonDto } from '@lingua-card/shared/domain';

export const STARTER_COLLECTIONS: AdminImportCollectionJsonDto[] = [
  {
    title: 'First Steps',
    level: 'A1',
    topic: 'daily-life',
    emoji: '🌱',
    words: [
      {
        back: 'Hallo',
        article: null,
        front: 'Hello',
        wordType: 'other',
        cefrLevel: 'A1',
        categoryName: 'Greetings',
        examples: [
          { target: 'Hallo, wie geht es dir?', native: 'Hello, how are you?' },
        ],
        synonyms: [
          { word: 'Guten Tag', translation: 'Good day' },
        ],
      },
      {
        back: 'Wasser',
        article: 'das',
        front: 'Water',
        plural: 'die Wasser',
        wordType: 'noun',
        cefrLevel: 'A1',
        categoryName: 'Food & Drink',
        examples: [
          { target: 'Ich möchte ein Glas Wasser, bitte.', native: 'I would like a glass of water, please.' },
        ],
      },
      {
        back: 'Brot',
        article: 'das',
        front: 'Bread',
        plural: 'die Brote',
        wordType: 'noun',
        cefrLevel: 'A1',
        categoryName: 'Food & Drink',
        examples: [
          { target: 'Wir kaufen frisches Brot.', native: 'We buy fresh bread.' },
        ],
      },
      {
        back: 'Haus',
        article: 'das',
        front: 'House',
        plural: 'die Häuser',
        wordType: 'noun',
        cefrLevel: 'A1',
        categoryName: 'Home',
        examples: [
          { target: 'Das Haus ist sehr groß.', native: 'The house is very big.' },
        ],
      },
      {
        back: 'Schule',
        article: 'die',
        front: 'School',
        plural: 'die Schulen',
        wordType: 'noun',
        cefrLevel: 'A1',
        categoryName: 'Education',
        examples: [
          { target: 'Die Kinder gehen in die Schule.', native: 'The children go to school.' },
        ],
      },
      {
        back: 'gut',
        article: null,
        front: 'Good',
        wordType: 'adjective',
        cefrLevel: 'A1',
        categoryName: 'Adjectives',
        examples: [
          { target: 'Das Essen ist sehr gut.', native: 'The food is very good.' },
        ],
        synonyms: [
          { word: 'toll', translation: 'Great' },
        ],
      },
      {
        back: 'Danke',
        article: null,
        front: 'Thank you',
        wordType: 'other',
        cefrLevel: 'A1',
        categoryName: 'Greetings',
        examples: [
          { target: 'Danke für deine Hilfe!', native: 'Thank you for your help!' },
        ],
      },
      {
        back: 'Freund',
        article: 'der',
        front: 'Friend',
        plural: 'die Freunde',
        wordType: 'noun',
        cefrLevel: 'A1',
        categoryName: 'People',
        examples: [
          { target: 'Er ist mein bester Freund.', native: 'He is my best friend.' },
        ],
        synonyms: [
          { word: 'Kumpel', article: 'der', translation: 'Buddy' },
        ],
      },
      {
        back: 'essen',
        article: null,
        front: 'To eat',
        wordType: 'verb',
        cefrLevel: 'A1',
        categoryName: 'Verbs',
        examples: [
          { target: 'Wir essen zusammen Abendessen.', native: 'We eat dinner together.' },
        ],
      },
      {
        back: 'Tag',
        article: 'der',
        front: 'Day',
        plural: 'die Tage',
        wordType: 'noun',
        cefrLevel: 'A1',
        categoryName: 'Time',
        examples: [
          { target: 'Heute ist ein schöner Tag.', native: 'Today is a beautiful day.' },
        ],
      },
    ],
  },
  {
    title: 'Everyday Life',
    level: 'A2',
    topic: 'daily-life',
    emoji: '🌿',
    words: [
      {
        back: 'Bahnhof',
        article: 'der',
        front: 'Train station',
        plural: 'die Bahnhöfe',
        wordType: 'noun',
        cefrLevel: 'A2',
        categoryName: 'Travel',
        examples: [
          { target: 'Der Zug fährt vom Bahnhof ab.', native: 'The train departs from the station.' },
        ],
      },
      {
        back: 'Rechnung',
        article: 'die',
        front: 'Bill / Invoice',
        plural: 'die Rechnungen',
        wordType: 'noun',
        cefrLevel: 'A2',
        categoryName: 'Shopping',
        examples: [
          { target: 'Kann ich bitte die Rechnung haben?', native: 'Can I have the bill, please?' },
        ],
      },
      {
        back: 'Wohnung',
        article: 'die',
        front: 'Apartment',
        plural: 'die Wohnungen',
        wordType: 'noun',
        cefrLevel: 'A2',
        categoryName: 'Home',
        examples: [
          { target: 'Meine Wohnung hat drei Zimmer.', native: 'My apartment has three rooms.' },
        ],
      },
      {
        back: 'Arzt',
        article: 'der',
        front: 'Doctor',
        plural: 'die Ärzte',
        wordType: 'noun',
        cefrLevel: 'A2',
        categoryName: 'Health',
        examples: [
          { target: 'Ich muss zum Arzt gehen.', native: 'I need to go to the doctor.' },
        ],
        synonyms: [
          { word: 'Ärztin', article: 'die', translation: 'Doctor (female)' },
        ],
      },
      {
        back: 'einkaufen',
        article: null,
        front: 'To go shopping',
        wordType: 'verb',
        cefrLevel: 'A2',
        categoryName: 'Verbs',
        examples: [
          { target: 'Ich gehe samstags einkaufen.', native: 'I go shopping on Saturdays.' },
        ],
      },
      {
        back: 'Nachricht',
        article: 'die',
        front: 'Message / News',
        plural: 'die Nachrichten',
        wordType: 'noun',
        cefrLevel: 'A2',
        categoryName: 'Communication',
        examples: [
          { target: 'Hast du meine Nachricht gelesen?', native: 'Did you read my message?' },
        ],
      },
      {
        back: 'Termin',
        article: 'der',
        front: 'Appointment',
        plural: 'die Termine',
        wordType: 'noun',
        cefrLevel: 'A2',
        categoryName: 'Time',
        examples: [
          { target: 'Ich habe morgen einen Termin beim Arzt.', native: 'I have a doctor\'s appointment tomorrow.' },
        ],
      },
      {
        back: 'billig',
        article: null,
        front: 'Cheap',
        wordType: 'adjective',
        cefrLevel: 'A2',
        categoryName: 'Adjectives',
        examples: [
          { target: 'Das Restaurant ist billig und gut.', native: 'The restaurant is cheap and good.' },
        ],
        synonyms: [
          { word: 'günstig', translation: 'Affordable' },
        ],
      },
      {
        back: 'Fahrkarte',
        article: 'die',
        front: 'Ticket (transport)',
        plural: 'die Fahrkarten',
        wordType: 'noun',
        cefrLevel: 'A2',
        categoryName: 'Travel',
        examples: [
          { target: 'Ich brauche eine Fahrkarte nach Berlin.', native: 'I need a ticket to Berlin.' },
        ],
      },
      {
        back: 'verstehen',
        article: null,
        front: 'To understand',
        wordType: 'verb',
        cefrLevel: 'A2',
        categoryName: 'Verbs',
        examples: [
          { target: 'Ich verstehe die Frage nicht.', native: 'I don\'t understand the question.' },
        ],
        synonyms: [
          { word: 'begreifen', translation: 'To comprehend' },
        ],
      },
    ],
  },
  {
    title: 'Growing Fluency',
    level: 'B1',
    topic: 'work-career',
    emoji: '🌳',
    words: [
      {
        back: 'Erfahrung',
        article: 'die',
        front: 'Experience',
        plural: 'die Erfahrungen',
        wordType: 'noun',
        cefrLevel: 'B1',
        categoryName: 'Work',
        examples: [
          { target: 'Sie hat viel Erfahrung in diesem Bereich.', native: 'She has a lot of experience in this field.' },
        ],
      },
      {
        back: 'Vorschlag',
        article: 'der',
        front: 'Suggestion / Proposal',
        plural: 'die Vorschläge',
        wordType: 'noun',
        cefrLevel: 'B1',
        categoryName: 'Communication',
        examples: [
          { target: 'Das ist ein guter Vorschlag.', native: 'That is a good suggestion.' },
        ],
      },
      {
        back: 'sich bewerben',
        article: null,
        front: 'To apply (for a job)',
        wordType: 'verb',
        cefrLevel: 'B1',
        categoryName: 'Work',
        examples: [
          { target: 'Ich möchte mich um die Stelle bewerben.', native: 'I would like to apply for the position.' },
        ],
      },
      {
        back: 'Zusammenhang',
        article: 'der',
        front: 'Context / Connection',
        plural: 'die Zusammenhänge',
        wordType: 'noun',
        cefrLevel: 'B1',
        categoryName: 'Abstract',
        examples: [
          { target: 'In diesem Zusammenhang ist das wichtig.', native: 'In this context, that is important.' },
        ],
      },
      {
        back: 'enttäuscht',
        article: null,
        front: 'Disappointed',
        wordType: 'adjective',
        cefrLevel: 'B1',
        categoryName: 'Emotions',
        examples: [
          { target: 'Er war enttäuscht über das Ergebnis.', native: 'He was disappointed about the result.' },
        ],
        synonyms: [
          { word: 'frustriert', translation: 'Frustrated' },
        ],
      },
      {
        back: 'Veranstaltung',
        article: 'die',
        front: 'Event',
        plural: 'die Veranstaltungen',
        wordType: 'noun',
        cefrLevel: 'B1',
        categoryName: 'Culture',
        examples: [
          { target: 'Die Veranstaltung findet am Samstag statt.', native: 'The event takes place on Saturday.' },
        ],
      },
      {
        back: 'empfehlen',
        article: null,
        front: 'To recommend',
        wordType: 'verb',
        cefrLevel: 'B1',
        categoryName: 'Verbs',
        examples: [
          { target: 'Können Sie mir ein Restaurant empfehlen?', native: 'Can you recommend a restaurant to me?' },
        ],
      },
      {
        back: 'Umgebung',
        article: 'die',
        front: 'Surroundings / Area',
        plural: 'die Umgebungen',
        wordType: 'noun',
        cefrLevel: 'B1',
        categoryName: 'Places',
        examples: [
          { target: 'Die Umgebung ist sehr ruhig und grün.', native: 'The surroundings are very quiet and green.' },
        ],
      },
      {
        back: 'Meinung',
        article: 'die',
        front: 'Opinion',
        plural: 'die Meinungen',
        wordType: 'noun',
        cefrLevel: 'B1',
        categoryName: 'Communication',
        examples: [
          { target: 'Was ist deine Meinung dazu?', native: 'What is your opinion on that?' },
        ],
        synonyms: [
          { word: 'Ansicht', article: 'die', translation: 'View / Point of view' },
        ],
      },
      {
        back: 'vergleichen',
        article: null,
        front: 'To compare',
        wordType: 'verb',
        cefrLevel: 'B1',
        categoryName: 'Verbs',
        examples: [
          { target: 'Man sollte die Preise vergleichen.', native: 'One should compare the prices.' },
        ],
      },
    ],
  },
  {
    title: 'Advanced Vocabulary',
    level: 'B2',
    topic: 'education',
    emoji: '🎓',
    words: [
      {
        back: 'Zusammenfassung',
        article: 'die',
        front: 'Summary',
        plural: 'die Zusammenfassungen',
        wordType: 'noun',
        cefrLevel: 'B2',
        categoryName: 'Academic',
        examples: [
          { target: 'Bitte schreiben Sie eine kurze Zusammenfassung.', native: 'Please write a short summary.' },
        ],
      },
      {
        back: 'berücksichtigen',
        article: null,
        front: 'To take into account / consider',
        wordType: 'verb',
        cefrLevel: 'B2',
        categoryName: 'Verbs',
        examples: [
          { target: 'Wir müssen alle Faktoren berücksichtigen.', native: 'We must take all factors into account.' },
        ],
        synonyms: [
          { word: 'beachten', translation: 'To pay attention to' },
        ],
      },
      {
        back: 'Herausforderung',
        article: 'die',
        front: 'Challenge',
        plural: 'die Herausforderungen',
        wordType: 'noun',
        cefrLevel: 'B2',
        categoryName: 'Abstract',
        examples: [
          { target: 'Das ist eine große Herausforderung.', native: 'That is a big challenge.' },
        ],
      },
      {
        back: 'Einfluss',
        article: 'der',
        front: 'Influence',
        plural: 'die Einflüsse',
        wordType: 'noun',
        cefrLevel: 'B2',
        categoryName: 'Abstract',
        examples: [
          { target: 'Das Internet hat einen großen Einfluss auf unser Leben.', native: 'The internet has a big influence on our lives.' },
        ],
      },
      {
        back: 'überzeugend',
        article: null,
        front: 'Convincing',
        wordType: 'adjective',
        cefrLevel: 'B2',
        categoryName: 'Adjectives',
        examples: [
          { target: 'Seine Argumentation war sehr überzeugend.', native: 'His argument was very convincing.' },
        ],
      },
      {
        back: 'Gesellschaft',
        article: 'die',
        front: 'Society / Company',
        plural: 'die Gesellschaften',
        wordType: 'noun',
        cefrLevel: 'B2',
        categoryName: 'Society',
        examples: [
          { target: 'Die Gesellschaft verändert sich ständig.', native: 'Society is constantly changing.' },
        ],
      },
      {
        back: 'voraussetzen',
        article: null,
        front: 'To presuppose / require',
        wordType: 'verb',
        cefrLevel: 'B2',
        categoryName: 'Verbs',
        examples: [
          { target: 'Der Job setzt Erfahrung voraus.', native: 'The job requires experience.' },
        ],
      },
      {
        back: 'Auseinandersetzung',
        article: 'die',
        front: 'Debate / Confrontation',
        plural: 'die Auseinandersetzungen',
        wordType: 'noun',
        cefrLevel: 'B2',
        categoryName: 'Communication',
        examples: [
          { target: 'Die Auseinandersetzung mit dem Thema ist wichtig.', native: 'Engaging with the topic is important.' },
        ],
      },
      {
        back: 'Entwicklung',
        article: 'die',
        front: 'Development',
        plural: 'die Entwicklungen',
        wordType: 'noun',
        cefrLevel: 'B2',
        categoryName: 'Abstract',
        examples: [
          { target: 'Die technologische Entwicklung geht schnell voran.', native: 'Technological development is advancing quickly.' },
        ],
      },
      {
        back: 'beeinflussen',
        article: null,
        front: 'To influence',
        wordType: 'verb',
        cefrLevel: 'B2',
        categoryName: 'Verbs',
        examples: [
          { target: 'Medien beeinflussen die öffentliche Meinung.', native: 'Media influence public opinion.' },
        ],
      },
    ],
  },
];
