import type { Story, StorySentence, WordTimestamp, StoryVocabWord } from '@lingua-card/shared/domain';

export const SEED_STORY: Omit<Story, 'id' | 'userId' | 'generatedAt' | 'listenCount' | 'lastListenedAt'> = {
  title: 'Ein Abend im Biergarten',
  titleTranslation: 'An Evening at the Beer Garden',
  bodyDe: 'Es war ein warmer Sommerabend als Thomas und Maria beschlossen, in den Biergarten zu gehen. Ich habe großen Hunger und Durst, sagte Thomas lachend. Der Kellner brachte ihnen sofort die Speisekarte. Maria betrachtete sie sorgfältig. Ich bestelle das Schnitzel, sagte sie. Thomas wählte die Tomatensuppe und eine Schorle. Am Ende des Abends bezahlten sie die Rechnung und gaben dem Kellner ein großzügiges Trinkgeld.',
  bodyNative: 'It was a warm summer evening when Thomas and Maria decided to go to the beer garden. I am very hungry and thirsty, said Thomas, laughing. The waiter immediately brought them the menu. Maria looked at it carefully. I will order the schnitzel, she said. Thomas chose the tomato soup and a sparkling water. At the end of the evening they paid the bill and gave the waiter a generous tip.',
  nativeLang: 'en',
  sentences: [
    { index: 0, german: 'Es war ein warmer Sommerabend als Thomas und Maria beschlossen, in den Biergarten zu gehen.', native: 'It was a warm summer evening when Thomas and Maria decided to go to the beer garden.', vocabWordIds: [] },
    { index: 1, german: 'Ich habe großen Hunger und Durst, sagte Thomas lachend.', native: 'I am very hungry and thirsty, said Thomas, laughing.', vocabWordIds: [] },
    { index: 2, german: 'Der Kellner brachte ihnen sofort die Speisekarte.', native: 'The waiter immediately brought them the menu.', vocabWordIds: [] },
    { index: 3, german: 'Ich bestelle das Schnitzel, sagte sie.', native: 'I will order the schnitzel, she said.', vocabWordIds: [] },
    { index: 4, german: 'Thomas wählte die Tomatensuppe und eine Schorle.', native: 'Thomas chose the tomato soup and a sparkling water.', vocabWordIds: [] },
    { index: 5, german: 'Am Ende des Abends bezahlten sie die Rechnung und gaben dem Kellner ein großzügiges Trinkgeld.', native: 'At the end of the evening they paid the bill and gave the waiter a generous tip.', vocabWordIds: [] },
  ] as StorySentence[],
  wordTimestamps: [] as WordTimestamp[],
  vocabWords: [
    { cardId: '', german: 'der Biergarten', germanBase: 'Biergarten', english: 'beer garden', article: 'der', sentenceIndices: [0] },
    { cardId: '', german: 'der Hunger', germanBase: 'Hunger', english: 'hunger', article: 'der', sentenceIndices: [1] },
    { cardId: '', german: 'der Durst', germanBase: 'Durst', english: 'thirst', article: 'der', sentenceIndices: [1] },
    { cardId: '', german: 'die Speisekarte', germanBase: 'Speisekarte', english: 'menu', article: 'die', sentenceIndices: [2] },
    { cardId: '', german: 'bestellen', germanBase: 'bestellen', english: 'to order', article: null, sentenceIndices: [3] },
    { cardId: '', german: 'das Schnitzel', germanBase: 'Schnitzel', english: 'schnitzel', article: 'das', sentenceIndices: [3] },
    { cardId: '', german: 'die Tomatensuppe', germanBase: 'Tomatensuppe', english: 'tomato soup', article: 'die', sentenceIndices: [4] },
    { cardId: '', german: 'die Schorle', germanBase: 'Schorle', english: 'spritzer / sparkling water', article: 'die', sentenceIndices: [4] },
    { cardId: '', german: 'bezahlen', germanBase: 'bezahlen', english: 'to pay', article: null, sentenceIndices: [5] },
    { cardId: '', german: 'die Rechnung', germanBase: 'Rechnung', english: 'bill / invoice', article: 'die', sentenceIndices: [5] },
    { cardId: '', german: 'das Trinkgeld', germanBase: 'Trinkgeld', english: 'tip (gratuity)', article: 'das', sentenceIndices: [5] },
  ] as StoryVocabWord[],
  audioUrl: null,
  audioDurationMs: 15000,
  sourceCollectionIds: [],
  difficultyLevel: 'A2',
  lengthType: 'medium',
  generationStatus: 'complete',
};
